// Create two dimensional array
var bingoList=new Array()
for (i=0; i < 4; i++)
{
	bingoList[i]=new Array()
}

// Simple
bingoList[0] = 
[
	{name :"4 Different Fish"},
	{name :"Enter the Nether"},
	{name :"5 Colours of Hardened Clay"},
	{name :"5 Mushroom Stew"},
	{name :"Activate a Button with an Arrow"},
	{name :"Book and Quill"},
	{name :"32 Flint"},
	{name :"Cake"},
	{name :"Pumpkin Pie"},
	{name :"Fish a Treasure and Junk item"},
	{name :"50 of Andesite, Granite, and/or Diorite"},
	{name :"30 Coarse Dirt"},
	{name :"2 Clocks"},
	{name :"3 Iron Blocks"},
	{name :"2 Gold Blocks"},
	{name :"Cyan Dye"},
	{name :"Golden Apple"},
	{name :"5 Bookshelves"},
	{name :"Never wear Chestplates"},
	{name :"Create a Jukebox"},
	{name :"25 Poppies & 25 Dandelions"},
	{name :"Build a glass cube and fill the inner with lava"},
	{name :"10 Mossy Cobblestone"},
	{name :"20 Cacti"},
	{name :"2 TNT"},
	{name :"Light Gray Dye + Light Blue Dye"},
	{name :"Level 10"},
	{name :"Power a Redstone Lamp"},
	{name :"Create a Snow Golem"},
	{name :"15 Note Blocks"},
	{name :"Build a 3x3x3 leaf cube"},
	{name :"15 Ink Sacks"},
	{name :"16 Bread"},
	{name :"5 colours of Wool"},
	{name :"9 Pistons"},
	{name :"Full Iron Armour"},
	{name :"Full Leather Armour"},
	{name :"Cauldron with Water"},
	{name :"Complete a Map"},
	{name :"32 Soul Sand"},
	{name :"22 Pumpkins"},
	{name :"40 Vines"},
	{name :"6 types of Slabs"},
	{name :"Every type of Sword"},
	{name :"Every type of Pickaxe"},
	{name :"32 Bricks (block)"},
	{name :"64 Arrows"},
	{name :"Enchanted Golden Sword"},
	{name :"Sleep in the Nether"},
	{name :"Fermented Spider Eye"},
	{name :"5 types of Stairs"},
	{name :"3 Ender Pearls"},
	{name :"16 Chicken Eggs"},
	{name :"Magenta Dye"},
	{name :"Hang up 3 different 4x4 Paintings"},
	{name :"5 Bone Blocks"},
]
// Moderate
bingoList[1] = 
[
	{name :"2 Wither Skulls"},
	{name :"7 Different Edible Items"},
	{name :"Build a Redstone AND Gate"},
	{name :"4 Different Gold Items"},
	{name :"Beetroot Soup"},
	{name :"10 Emeralds"},
	{name :"Trade with a Villager"},
	{name :"Water Bucket, Lava Bucket and Milk Bucket"},
	{name :"Tame a Horse"},
	{name :"Place a Cactus in a Flower Pot"},
	{name :"Ignite a TNT-Minecart"},
	{name :"12 Magma Blocks"},
	{name :"Skull and Crossbones Banner"},
	{name :"Cookie"},
	{name :"Very Damaged Anvil"},
	{name :"15 Melons"},
	{name :"Sleep inside a village"},
	{name :"Kill a Skeleton with it's own Arrow"},
	{name :"Never wear Armour"},
	{name :"Take a Skeleton's Bow"},
	{name :"9 Bookshelves"},
	{name :"Diamond Block"},
	{name :"2 Lapis Lazuli Blocks"},
	{name :"Destroy a Monster Spawner"},
	{name :"Level 20"},
	{name :"4 types of Saplings"},
	{name :"Tame an ocelot"},
	{name :"Tame a wolf"},
	{name :"15 Fire Charges"},
	{name :"3 Magma Creams"},
	{name :"Potion of Fire Resistance"},
	{name :"Potion of Healing"},
	{name :"Grow a full jungle Tree"},
	{name :"Potion of Poison"},
	{name :"Potion of Harming"},
	{name :"Create an Iron Golem"},
	{name :"Potion of Regeneration"},
	{name :"Potion of Slowness"},
	{name :"Eye of Ender"},
	{name :"Potion of Strength"},
	{name :"Potion of Swiftness"},
	{name :"Music Disc"},
	{name :"Potion of Weakness"},
]

// Hard
bingoList[2] = 
[
	{name :"Grass Block"},
	{name :"Create a Level 10+ enchantment"},
	{name :"Sea Lantern"},
	{name :"3 Sponges"},
	{name :"Bounce on a Slime Block"},
	{name :"Rabbit Stew"},
	{name :"Listen to a Music Disc"},
	{name :"1 of Every Ore (Silk Touch)"},
	{name :"Capture a Zombie, Skeleton and a Creeper"},
	{name :"5 Different Potions"},
	{name :"Cure a Zombie Villager"},
	{name :"9 Different Flowers"},
	{name :"Block of Iron, Gold and Diamond on top each other"},
	{name :"Take a Zombie Pigman's Sword"},
	{name :"Every type of Chestplate"},
]

// Silly
bingoList[3] = 
[
	{name :"Finish by jumping from top to bottom of the world"},
	{name :"Finish launching Fireworks of 5 different colors"},
	{name :"Nametag an Enderman"},
	{name :"Never Eat Meat (including Fish)"},
	{name :"Kill yourself with your own arrow"},
	{name :"Kill yourself with an Ender Pearl"},
	{name :"Get a '... while trying to escape ...' Death message"},
	{name :"Kill a mob with an Anvil"},
	{name :"Burn down a village"},
	{name :"Kill yourself by starving"},
	{name :"Finish on top of the world"},
	{name :"Finish where you spawned (compass)"},
	{name :"Finish on top of a Blaze spawner"},
]