// Create two dimensional array
var bingoList=new Array()
for (i=0; i < 4; i++)
{
	bingoList[i]=new Array()
}

// Simple
bingoList[0] = 
[
	{name :"(3-4) Different Fish"},
	{name :"Grow a Tree in the Nether"},
	{name :"(5-10) Colours of Hardened Clay"},
	{name :"(1-5) Mushroom Stew"},
	{name :"Activate a Button with an Arrow"},
	{name :"Book and Quill"},
	{name :"(16-64) Flint"},
	{name :"Cake"},
	{name :"Pumpkin Pie"},
	{name :"Fish a Treasure and Junk item"},
	{name :"(10-30) Andesite, Granite, or Diorite"},
	{name :"(16-64) Coarse Dirt"},
	{name :"(2-3) Clocks"},
	{name :"(2-4) Iron Blocks"},
	{name :"(2-4) Gold Blocks"},
	{name :"Cyan Dye"},
	{name :"Golden Apple"},
	{name :"(2-4) Bookshelves"},
	{name :"Never wear Chestplates"},
	{name :"Jukebox"},
	{name :"(5-25) Poppies & (5-25) Dandelions"},
	{name :"Build a glass cube and fill the inner with lava"},
	{name :"(10-30) Mossy Cobblestone"},
	{name :"(10-30) Cacti"},
	{name :"(1-3) TNT", tooltiptext:"TNT goes boom"},
	{name :"Light Gray Dye and Light Blue Dye"},
	{name :"Level (10-20)"},
	{name :"Power a Redstone Lamp"},
	{name :"Create a Snow Golem"},
	{name :"(10-30) Note Blocks"},
	{name :"Build a (2-4)x(2-4)x(2-4) leaf cube"},
	{name :"(10-30) Ink Sacks"},
	{name :"(10-30) Bread"},
	{name :"(5-10) colours of Wool"},
	{name :"(5-10) Pistons"},
	{name :"Full Iron Armour"},
	{name :"Full Leather Armour"},
	{name :"Full Gold Armour"},
	{name :"Cauldron with Water"},
	{name :"Complete a Map"},
	{name :"(16-64) Soul Sand"},
	{name :"(10-30) Pumpkins"},
	{name :"(10-30) Vines"},
	{name :"(6-8) Different Slabs"},
	{name :"Every type of Sword"},
	{name :"Every type of Pickaxe"},
	{name :"(16-64) Brick Blocks"},
	{name :"(16-64) Arrows"},
	{name :"Enchanted Golden Sword"},
	{name :"Sleep in the Nether"},
	{name :"Fermented Spider Eye"},
	{name :"(5-7) Different Stairs"},
	{name :"(2-4) Ender Pearls"},
	{name :"16 Chicken Eggs"},
	{name :"Magenta Dye"},
	{name :"Hang up 3 Different 4x4 Paintings"},
	{name :"(5-10) Bone Blocks"},
	{name :"2 Creepers in the same Boat"},
	{name :"Trade with a Villager"},
]
// Moderate
bingoList[1] = 
[
	{name :"Wither Skull"},
	{name :"(6-8) Different Edible Items"},
	{name :"Build a Redstone AND Gate"},
	{name :"(3-5) Different Gold Items"},
	{name :"Beetroot Soup"},
	{name :"(2-15) Emeralds"},
	{name :"Water Bucket, Lava Bucket and Milk Bucket"},
	{name :"Tame a Horse"},
	{name :"Place a Cactus in a Flower Pot"},
	{name :"Ignite a TNT-Minecart"},
	{name :"(10-30) Magma Blocks"},
	{name :"Skull and Crossbones Banner", tooltipimg: "https://hydra-media.cursecdn.com/minecraft.gamepedia.com/thumb/8/87/Banner.png/100px-Banner.png?version=6db5087d8053de49c30e59554995755b"},
	{name :"Cookie"},
	{name :"Very Damaged Anvil"},
	{name :"(16-64) Melons"},
	{name :"Sleep inside a village"},
	{name :"Kill a Skeleton with it's own Arrow"},
	{name :"Never wear any Armour"},
	{name :"Get a Skeleton's Bow"},
	{name :"Diamond Block"},
	{name :"(2-3) Lapis Lazuli Blocks"},
	{name :"Destroy a Monster Spawner"},
	{name :"(2-5) Different Saplings"},
	{name :"Tame an Ocelot"},
	{name :"Tame a Wolf"},
	{name :"9 Fire Charges"},
	{name :"(2-5) Magma Creams"},
	{name :"Grow a full jungle Tree"},
	{name :"Create an Iron Golem"},
	{name :"Eye of Ender"},
	{name :"Potion of Fire Resistance"},
	{name :"Potion of Healing"},
	{name :"Potion of Poison"},
	{name :"Potion of Harming"},
	{name :"Potion of Regeneration"},
	{name :"Potion of Slowness"},
	{name :"Potion of Strength"},
	{name :"Potion of Swiftness"},
	{name :"Potion of Weakness"},
	{name :"Rabbit Stew"},
]

// Hard
bingoList[2] = 
[
	{name :"Grass Block"},
	{name :"Create an Enchantment requiring level 10+"},
	{name :"Sea Lantern", tooltipimg: "https://hydra-media.cursecdn.com/minecraft.gamepedia.com/0/07/Sea_Lantern.gif?version=e3e7a8781710aae7f5b1070931e6d49a", tooltiptext:"Hello World"},
	{name :"(2-4) Sponges"},
	{name :"Bounce on a Slime Block"},
	{name :"Listen to a Music Disc"},
	{name :"(5-8) Different Ores (Silk Touch)"},
	{name :"(2-5) Different Potions"},
	{name :"Cure a Zombie Villager"},
	{name :"(11-13) Different Flowers"},
	{name :"Place an Iron, Gold and Diamond block on top of each other"},
	{name :"Get a Zombie Pigman's Sword"},
	{name :"Every type of Chestplate"},
]

// Silly
bingoList[3] = 
[
	{name :"Finish by jumping from top to bottom of the world"},
	{name :"Finish launching Fireworks of (5-10) Colors"},
	{name :"Nametag an Enderman"},
	{name :"Never Eat Meat (including Fish)"},
	{name :"Kill yourself with your own arrow"},
	{name :"Kill yourself with an Ender Pearl"},
	{name :"Get a '... while trying to escape ...' Death message"},
	{name :"Kill a mob with an Anvil"},
	{name :"Set fire to a Villager's House"},
	{name :"Kill yourself by starving"},
	{name :"Finish on top of the world"},
	{name :"Finish where you spawned (compass)"},
	{name :"Finish on top of a Blaze spawner"},
]