// This is part of a version currently in development and may be changed at any time.

// Tags
var Item = {name: "Item", max: [24, 23, 20, 20, 20], line: true},
Stat = {name: "Stat", max: [5, 5, 5, 5, 5], line: true},
Action = {name: "Action", max: [15, 15, 15, 15, 15], line: true},
Build = {name: "Build", max: [5, 5, 5, 5, 5], line: true},
// note, that on lower difficulties, RareBiome means "Specific Biome"
RareBiome = {name: "RareBiome", max: [1, 2, 3, 4, 6], line: true},
Ocean = {name: "Ocean", max: [5, 5, 5, 5, 5], line: true},
Village = {name: "Village", max: [0, 1, 2, 2, 2], line: true},
Colour = {name: "Colour", max: [2, 2, 2, 2, 2], line: true},
Never = {name: "Never", max: [3, 3, 3, 2, 1], line: false},
Combat = {name: "Combat", max: [5, 10, 20, 20, 20], line: true},
Overworld = {name: "Overworld", max: [25, 25, 23, 21, 18], line: true},
Nether = {name: "Nether", max: [0, 2, 5, 10, 15], line: true},
End = {name: "End", max: [0, 0, 0, 1, 5], line: true},
Finish = {name: "Finish", max: [1, 1, 1, 1, 1], line: true},
Netherite = {name: "Netherite", max: [0, 0, 0, 1, 3], line: true};

// New Points System Tags
var Wood = {name: "Wood", max: [4, 3, 2, 1, 0], line: false},
Ore = {name: "Ore", max: [5, 4, 3, 2, 1], line: true},
Tool = {name: "Tool", max: [5, 4, 3, 2, 1], line: true}, // And weapons
Food = {name: "Food", max: [5, 4, 3, 2, 1], line: true};

var bingoList_v5 = [
	//New Points System
	// Duplicate nammed goals should be avoided by the generator so less "AntiSynergy" between the same named goal should be unecerssary
	
	//#region Dirt
	{name: "(33-48) Dirt", difficulty: 1, infrequency: 2, tags: [Item, Overworld]},
	{name: "(49-64) Dirt", difficulty: 2, infrequency: 2, tags: [Item, Overworld]},
	{name: "(9-16) Coarse Dirt", difficulty: 3, infrequency: 4, tags: [Item, Overworld]},
	{name: "(17-32) Coarse Dirt", difficulty: 4, infrequency: 4, tags: [Item, Overworld]},
	{name: "(33-48) Coarse Dirt", difficulty: 5, infrequency: 4, tags: [Item, Overworld]},
	{name: "(49-64) Coarse Dirt", difficulty: 6, infrequency: 4, tags: [Item, Overworld]},
	{name: "Grass Block", difficulty: 14, tooltiptext: "If you don't have Silk Touch, I know a guy who might pick one up for you...", tooltipimg: "Goal Tooltip Images/GrassBlock.jpg", tags: [Item, Overworld]},
	//#endregion

	//#region Stone
	{name: "(17-32) Cobblestone", difficulty: 1, infrequency: 3, tags: [Item, Overworld]},
	{name: "(33-48) Cobblestone", difficulty: 2, infrequency: 3, tags: [Item, Overworld]},
	{name: "(49-64) Cobblestone", difficulty: 3, infrequency: 3, tags: [Item, Overworld]},
	{name: "(17-32) Stone", difficulty: 3, tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", infrequency: 3, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(33-48) Stone", difficulty: 4, tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", infrequency: 3, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(49-64) Stone", difficulty: 5, tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", infrequency: 3, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(17-32) Smooth Stone", difficulty: 4, infrequency: 3, tags: [Item, Overworld]},
	{name: "(33-48) Smooth Stone", difficulty: 5, infrequency: 3, tags: [Item, Overworld]},
	{name: "(49-64) Smooth Stone", difficulty: 6, infrequency: 3, tags: [Item, Overworld]},
	{name: "(17-32) Andesite", difficulty: 3, infrequency: 3, tags: [Item, Overworld]},
	{name: "(33-48) Andesite", difficulty: 4, infrequency: 3, tags: [Item, Overworld]},
	{name: "(49-64) Andesite", difficulty: 5, infrequency: 3, tags: [Item, Overworld]},
	{name: "(17-32) Granite", difficulty: 3, infrequency: 3, tags: [Item, Overworld]},
	{name: "(33-48) Granite", difficulty: 4, infrequency: 3, tags: [Item, Overworld]},
	{name: "(49-64) Granite", difficulty: 5, infrequency: 3, tags: [Item, Overworld]},
	{name: "(17-32) Diorite", difficulty: 3, infrequency: 3, tags: [Item, Overworld]},
	{name: "(33-48) Diorite", difficulty: 4, infrequency: 3, tags: [Item, Overworld]},
	{name: "(49-64) Diorite", difficulty: 5, infrequency: 3, tags: [Item, Overworld]},
	{name: "(16-32) Mossy Cobblestone", difficulty: 10, tags: [Item, Overworld]}, // not RareBiome, because can be found in a Plains Village
	//#endregion

	//#region Wood
	{name: "(7-16) Oak Logs", difficulty: 1, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Oak Logs", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Oak Logs", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Oak Logs", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Birch Logs", difficulty: 1, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Birch Logs", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Birch Logs", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Birch Logs", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Spruce Logs", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Spruce Logs", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Spruce Logs", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Spruce Logs", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Acacia Logs", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Acacia Logs", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Acacia Logs", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Acacia Logs", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Dark Oak Logs", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Dark Oak Logs", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Dark Oak Logs", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Dark Oak Logs", difficulty: 6, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Warped Stem", difficulty: 11, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(17-32) Warped Stem", difficulty: 12, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(33-48) Warped Stem", difficulty: 13, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-64) Warped Stem", difficulty: 14, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(7-16) Crimson Stem", difficulty: 11, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(17-32) Crimson Stem", difficulty: 12, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(33-48) Crimson Stem", difficulty: 13, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-64) Crimson Stem", difficulty: 14, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(7-16) Jungle Logs", difficulty: 21, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Jungle Logs", difficulty: 22, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Jungle Logs", difficulty: 23, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Jungle Logs", difficulty: 24, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-64) Oak Planks", difficulty: 1, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(65-128) Oak Planks", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-64) Birch Planks", difficulty: 1, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(65-128) Birch Planks", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-64) Spruce Planks", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(65-128) Spruce Planks", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-64) Acacia Planks", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(65-128) Acacia Planks", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-64) Dark Oak Planks", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(65-128) Dark Oak Planks", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-64) Warped Planks", difficulty: 11, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(65-128) Warped Planks", difficulty: 12, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(33-64) Crimson Planks", difficulty: 11, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(65-128) Crimson Planks", difficulty: 12, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(33-64) Jungle Planks", difficulty: 21, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(65-128) Jungle Planks", difficulty: 22, infrequency: 9, tags: [Item, Overworld, Wood]},	
	{name: "(5-12) Oak Wood", difficulty: 1, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Oak Wood", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Oak Wood", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Oak Wood", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Oak Wood", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Birch Wood", difficulty: 1, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Birch Wood", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Birch Wood", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Birch Wood", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Birch Wood", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Spruce Wood", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Spruce Wood", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Spruce Wood", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Spruce Wood", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Spruce Wood", difficulty: 6, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Acacia Wood", difficulty: 2, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Acacia Wood", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Acacia Wood", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Acacia Wood", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Acacia Wood", difficulty: 6, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Dark Oak Wood", difficulty: 3, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Dark Oak Wood", difficulty: 4, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Dark Oak Wood", difficulty: 5, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Dark Oak Wood", difficulty: 6, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Dark Oak Wood", difficulty: 7, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Warped Hyphae", difficulty: 11, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(13-24) Warped Hyphae", difficulty: 12, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(25-36) Warped Hyphae", difficulty: 13, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(37-48) Warped Hyphae", difficulty: 14, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-60) Warped Hyphae", difficulty: 15, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(5-12) Crimson Hyphae", difficulty: 11, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(13-24) Crimson Hyphae", difficulty: 12, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(25-36) Crimson Hyphae", difficulty: 13, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(37-48) Crimson Hyphae", difficulty: 14, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-60) Crimson Hyphae", difficulty: 15, infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(5-12) Jungle Wood", difficulty: 21, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Jungle Wood", difficulty: 22, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Jungle Wood", difficulty: 23, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Jungle Wood", difficulty: 24, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Jungle Wood", difficulty: 25, infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Stripped Oak Logs", difficulty: 2, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Stripped Oak Logs", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Stripped Oak Logs", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Stripped Oak Logs", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Stripped Birch Logs", difficulty: 2, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Stripped Birch Logs", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Stripped Birch Logs", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Stripped Birch Logs", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Stripped Spruce Logs", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Stripped Spruce Logs", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Stripped Spruce Logs", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Stripped Spruce Logs", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Stripped Acacia Logs", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Stripped Acacia Logs", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Stripped Acacia Logs", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Stripped Acacia Logs", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Stripped Dark Oak Logs", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Stripped Dark Oak Logs", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Stripped Dark Oak Logs", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Stripped Dark Oak Logs", difficulty: 7, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(7-16) Stripped Warped Stem", difficulty: 12, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(17-32) Stripped Warped Stem", difficulty: 13, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(33-48) Stripped Warped Stem", difficulty: 14, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-64) Stripped Warped Stem", difficulty: 15, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(7-16) Stripped Crimson Stem", difficulty: 12, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(17-32) Stripped Crimson Stem", difficulty: 13, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(33-48) Stripped Crimson Stem", difficulty: 14, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-64) Stripped Crimson Stem", difficulty: 15, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(7-16) Stripped Jungle Logs", difficulty: 22, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(17-32) Stripped Jungle Logs", difficulty: 23, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(33-48) Stripped Jungle Logs", difficulty: 24, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-64) Stripped Jungle Logs", difficulty: 25, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Stripped Oak Wood", difficulty: 2, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Stripped Oak Wood", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Stripped Oak Wood", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Stripped Oak Wood", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Stripped Oak Wood", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Stripped Birch Wood", difficulty: 2, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Stripped Birch Wood", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Stripped Birch Wood", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Stripped Birch Wood", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Stripped Birch Wood", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Stripped Spruce Wood", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Stripped Spruce Wood", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Stripped Spruce Wood", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Stripped Spruce Wood", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Stripped Spruce Wood", difficulty: 7, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Stripped Acacia Wood", difficulty: 3, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Stripped Acacia Wood", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Stripped Acacia Wood", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Stripped Acacia Wood", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Stripped Acacia Wood", difficulty: 7, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Stripped Dark Oak Wood", difficulty: 4, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Stripped Dark Oak Wood", difficulty: 5, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Stripped Dark Oak Wood", difficulty: 6, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Stripped Dark Oak Wood", difficulty: 7, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Stripped Dark Oak Wood", difficulty: 8, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(5-12) Stripped Warped Hyphae", difficulty: 12, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(13-24) Stripped Warped Hyphae", difficulty: 13, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(25-36) Stripped Warped Hyphae", difficulty: 14, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(37-48) Stripped Warped Hyphae", difficulty: 15, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-60) Stripped Warped Hyphae", difficulty: 16, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(5-12) Stripped Crimson Hyphae", difficulty: 12, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(13-24) Stripped Crimson Hyphae", difficulty: 13, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(25-36) Stripped Crimson Hyphae", difficulty: 14, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(37-48) Stripped Crimson Hyphae", difficulty: 15, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(49-60) Stripped Crimson Hyphae", difficulty: 16, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Nether, Wood]},
	{name: "(5-12) Stripped Jungle Wood", difficulty: 22, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(13-24) Stripped Jungle Wood", difficulty: 23, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(25-36) Stripped Jungle Wood", difficulty: 24, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(37-48) Stripped Jungle Wood", difficulty: 25, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(49-60) Stripped Jungle Wood", difficulty: 26, reactant: ["AxeUse"], infrequency: 9, tags: [Item, Overworld, Wood]},
	{name: "(32-64) Sticks", difficulty: 1, infrequency: 2, tags: [Item, Wood]},
	//#endregion

	//#region Ores
	{name: "Iron Block", difficulty: 4, infrequency: 3, tags: [Item, Ore]},
	{name: "3 Iron Blocks", difficulty: 8, infrequency: 3, tags: [Item, Ore]},
	{name: "5 Iron Blocks", difficulty: 12, infrequency: 3, tags: [Item, Ore]},
	{name: "Gold Block", difficulty: 5, infrequency: 3, tags: [Item, Ore]},
	{name: "3 Gold Blocks", difficulty: 10, infrequency: 3, tags: [Item, Ore]},
	{name: "5 Gold Blocks", difficulty: 15, infrequency: 3, tags: [Item, Ore]},
	{name: "Diamond", difficulty: 9, tags: [Item]},
	{name: "Diamond Block", difficulty: 11, infrequency: 3, tags: [Item, Ore]},
	{name: "3 Diamond Blocks", difficulty: 17, infrequency: 3, tags: [Item, Ore]},
	{name: "5 Diamond Blocks", difficulty: 25, infrequency: 3, tags: [Item, Ore]},
	{name: "Redstone Block", difficulty: 6, infrequency: 3, tags: [Item, Overworld, Ore]},
	{name: "3 Redstone Blocks", difficulty: 12, infrequency: 3, tags: [Item, Overworld, Ore]},
	{name: "5 Redstone Blocks", difficulty: 18, infrequency: 3, tags: [Item, Overworld, Ore]},
	{name: "Lapis Lazuli Block", difficulty: 6, tags: [Item, Overworld, Ore]},
	{name: "3 Lapis Lazuli Blocks", difficulty: 12, tags: [Item, Overworld, Ore]},
	{name: "5 Lapis Lazuli Blocks", difficulty: 18, tags: [Item, Overworld, Ore]},
	{name: "Block of Coal", difficulty: 3, reactant: ["NeverCoal"], tags: [Item, Ore]},
	{name: "3 Blocks of Coal", difficulty: 6, reactant: ["NeverCoal"], tags: [Item, Ore]},
	{name: "5 Blocks of Coal", difficulty: 9, reactant: ["NeverCoal"], tags: [Item, Ore]},
	{name: "(32-64) Iron Nuggets", difficulty: 4, tags: [Item, Ore]},
	{name: "(32-64) Gold Nuggets", difficulty: 5, tags: [Item, Ore]},
	{name: "Emerald", difficulty: 8, tags: [Item, Overworld, Ore]},
	//#endregion

	//#region Tools (and weapons)
	{name: "Lava Bucket", difficulty: 4, antisynergy: ["LavaBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Tool]},
	{name: "Milk Bucket", difficulty: 4, antisynergy: ["MilkBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Overworld, Tool]},
	{name: "Water Bucket", difficulty: 4, antisynergy: ["WaterBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Overworld, Tool]},
	{name: "Bucket of Fish", difficulty: 4, antisynergy: ["FishBucket"], reactant: ["UseBuckets"], infrequency: 4, tooltiptext: "Can be any of the types of Fish.", tooltipimg: "Goal Tooltip Images/FishBucket.jpg", tags: [Item, Ocean, Overworld, Tool]},
	{name: "Fishing Rod", difficulty: 3, tags: [Item, Tool]},
	{name: "Deplete a Hoe", difficulty: 1, tooltiptext: "Use a Hoe until it breaks, check the 'Items' statistics screen!", tags: [Action, Stat]},
	{name: "(9-16) Arrows", difficulty: 5, tags: [Item, Tool]}, // 2 + 1 + 2
	{name: "(17-32) Arrows", difficulty: 6, tags: [Item, Tool]},
	{name: "Clock", difficulty: 11, tags: [Item, Overworld, Tool]},
	{name: "Wooden, Stone, Gold, Iron and Diamond Sword", difficulty: 14, infrequency: 2, antisynergy: ["EverySword"], tags: [Item, Tool]},
	{name: "Wooden, Stone, Gold, Iron and Diamond Pickaxe", difficulty: 14, infrequency: 2, antisynergy: ["EveryPickaxe"], tags: [Item, Tool]},
	{name: "Water, Lava and Milk Bucket", difficulty: 8, antisynergy: ["BucketTypes", "WaterBucket", "LavaBucket", "MilkBucket"], reactant: ["UseBuckets"], tags: [Item, Overworld, Tool]},
	{name: "Finish where you spawned using a Compass", difficulty: 13, tooltiptext: "Be stood close enough to spin your compass within a couple blocks at the end of the game.", tooltipimg: "Goal Tooltip Images/Compass.jpg", tags: [Action, Overworld, Finish, Tool]},
	{name: "Carrot on a Stick", difficulty: 10, tags: [Item, Tool]},
	{name: "Enchanted Golden Sword", difficulty: 10, tags: [Item, Tool]},
	{name: "Water, Lava, Milk and Fish Bucket", difficulty: 10, antisynergy: ["BucketTypes", "WaterBucket", "LavaBucket", "MilkBucket", "FishBucket"], reactant: ["UseBuckets"], tooltiptext: "Can be any of the types of Fish.", tooltipimg: "Goal Tooltip Images/FishBucket.jpg", tags: [Item, Overworld, Tool]},
	{name: "Blue Shield with White Flower Charge Pattern", difficulty: 14, tags: [Item, Overworld, Tool]},
	//#endregion

	//#region Vegetation
	{name: "(5-16) Poppies & (5-16) Dandelions", difficulty: 1, infrequency: 2, tags: [Item, Overworld]},
	{name: "(17-32) Poppies & (17-32) Dandelions", difficulty: 2, infrequency: 2, tags: [Item, Overworld]},
	{name: "(32-64) Leaves", difficulty: 5, tags: [Item, Overworld]},
	{name: "Pumpkin", difficulty: 4, tags: [Item, Overworld]},
	{name: "(5-16) Cacti", difficulty: 10, tags: [Item, RareBiome, Overworld]},
	{name: "Pumpkin", difficulty: 4, tags: [Item, Overworld]},
	{name: "Carved Pumpkin", difficulty: 5, tags: [Item, Overworld]},
	{name: "(17-32) Vines", difficulty: 10, tags: [Item, RareBiome, Overworld]},
	{name: "Dead Bush", difficulty: 10, tags: [Item, RareBiome, Overworld]},
	{name: "(15-32) Grass", difficulty: 5, tooltiptext: "The tall stuff, NOT the block.", tooltipimg: "Goal Tooltip Images/TallGrass.jpg", tags: [Item, Overworld]},
	{name: "Grow a Huge Mushroom", difficulty: 10, tags: [Action]},
	{name: "(5-7) Different Flowers", difficulty: 9, antisynergy: ["Flowers"], infrequency: 3, tags: [Item, Overworld]},
	{name: "(8-9) Different Flowers", difficulty: 12, antisynergy: ["Flowers"], infrequency: 3, tags: [Item, Overworld]},
	{name: "(10-11) Different Flowers", difficulty: 15, antisynergy: ["Flowers"], infrequency: 3, tags: [Item, Overworld]},
	{name: "(11-14) Different Flowers", difficulty: 20, antisynergy: ["Flowers"], infrequency: 3, tags: [Item, RareBiome, Overworld]},
	{name: "(2-10) Lily Pads", difficulty: 10, tags: [Item, RareBiome, Overworld]},
	{name: "3 Different Saplings", difficulty: 10,  tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld]},
	{name: "4 Different Saplings", difficulty: 12,  tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld]},
	{name: "5 Different Saplings", difficulty: 15,  tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld]},
	{name: "6 Different Saplings", difficulty: 18,  tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld]},
	{name: "7 Different Saplings", difficulty: 22,  tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld, RareBiome]},
	{name: "8 Different Saplings", difficulty: 30,  tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld, RareBiome]},
	{name: "2 Different Seeds", difficulty: 6, infrequency: 2, antisynergy: ["Seeds"], tooltiptext: "Any item with \"Seeds\" in the name.", tags: [Item, Overworld]},
	{name: "3 Different Seeds", difficulty: 10, infrequency: 2, antisynergy: ["Seeds"], tooltiptext: "Any item with \"Seeds\" in the name.", tags: [Item, Overworld]},
	{name: "4 Different Seeds", difficulty: 25, infrequency: 2, antisynergy: ["Seeds"], tooltiptext: "Any item with \"Seeds\" in the name.", tags: [Item, Overworld]},
	{name: "(6-15) Bamboo", difficulty: 20, tags: [Item, Overworld, RareBiome]},
	//#endregion

	//#region Stats
	{name: "Level (5-7)", difficulty: 2, infrequency: 2, tags: [Stat]},
	{name: "Level (8-15)", difficulty: 5, infrequency: 2, tags: [Stat]},
	{name: "Level (16-25)", difficulty: 12, infrequency: 2, tags: [Stat]},
	{name: "Level (26-35)", difficulty: 24, infrequency: 2, tags: [Stat]},
	{name: "Level (46-50)", difficulty: 34, infrequency: 2, tags: [Stat]},
	{name: "Breed a set of animals", difficulty: 2, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 3, tags: [Action, Stat]},
	{name: "Breed (2-4) sets of animals", difficulty: 4, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 3, tags: [Action, Stat]},
	{name: "Breed (5-7) sets of animals", difficulty: 6, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 3, tags: [Action, Stat]},
	{name: "Breed (8-10) sets of animals", difficulty: 8, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 3, tags: [Action, Stat]},
	{name: "Crouch a distance of (50-100) meters", difficulty: 3, tooltiptext: "Check the 'General' statistics screen!", infrequency: 2, tags: [Action, Stat]},
	{name: "Kill (10-25) mobs", difficulty: 3, reactant: ["Pacifist"], tooltiptext: "Check the 'General' statistics screen!", infrequency: 3, tags: [Action, Combat, Stat]},
	{name: "Kill (26-50) mobs", difficulty: 5, reactant: ["Pacifist"], tooltiptext: "Check the 'General' statistics screen!", infrequency: 3, tags: [Action, Combat, Stat]},
	{name: "Kill (51-75) mobs", difficulty: 7, reactant: ["Pacifist"], tooltiptext: "Check the 'General' statistics screen!", infrequency: 3, tags: [Action, Combat, Stat]},
	{name: "Kill (76-100) mobs", difficulty: 9, reactant: ["Pacifist"], tooltiptext: "Check the 'General' statistics screen!", infrequency: 3, tags: [Action, Combat, Stat]},
	//#endregion

	//#region Action and Builds
	{name: "Build a (2-4)x(2-4)x(2-4) leaf cube", difficulty: 6, tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/LeafCube.jpg", tags: [Build, Overworld]},
	{name: "Sleep in a Bed", difficulty: 3, reactant: ["Sleep"], tags: [Action, Overworld]},
	{name: "Bounce on a Bed", difficulty: 3, tags: [Action, Overworld]},
	{name: "Fill all 4 slots of a Campfire", difficulty: 4, tags: [Action, Food]},
	{name: "Extinguish a Campfire", difficulty: 3, tags: [Action]},
	{name: "Change the colour of text on a Sign", difficulty: 2, tags: [Action]},
	{name: "Hang up a Painting", difficulty: 2, antisynergy: ["Painting"], tags: [Action, Overworld]},
	{name: "Fill a Composter", difficulty: 3, tooltiptext: "Add stuff until you can get Bonemeal out!", tooltipimg: "Goal Tooltip Images/FullComposter.jpg", tags: [Action]},
	{name: "Shoot a Button with an Arrow", difficulty: 5, tags: [Action]},
	{name: "Fish a Treasure and a Junk item", difficulty: 11, tooltiptext: "Treasure: Bow, Enchanted Book, Name Tag, Nautilus Shell, Saddle. Junk: Lily Pad, Bone, Bowl, Leather, Boots, Rotten Flesh, Stick, Water Bottle, Ink Sac, Tripwire Hook", reactant: ["Fishing"], tags: [Action, Overworld]},
	{name: "Build a 3x3x3 Glass cube and fill the middle with Lava", difficulty: 6, tags: [Build, Overworld]}, // 4 + 2
	{name: "Create a Snow Golem", difficulty: 12, tags: [Action, RareBiome, Overworld]},
	{name: "Extend a Piston", difficulty: 12, tags: [Action, Overworld]},
	{name: "Fill a Cauldron with Water", difficulty: 5, tags: [Action, Overworld]},
	{name: "Complete a Map", difficulty: 9, antisynergy: ["CompleteMap"], tags: [Action, Overworld]},
	{name: "Hang up 3 Different 4x4 Paintings", difficulty: 5, antisynergy: ["Painting"], tags: [Action, Overworld]},
	{name: "2 Creepers in the same Boat", difficulty: 7, tooltiptext: "The 2 Creepers must be in the same boat at the same time.", tooltipimg: "Goal Tooltip Images/2creepers1boat.jpg", tags: [Action, Combat, Overworld]},
	{name: "Trade with a Villager", difficulty: 6, tags: [Village, Action, Overworld]},
	{name: "Crouch a distance of (100-200) meters", difficulty: 6, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Ring a Bell from 10 blocks away", difficulty: 5, tags: [Action, Village, Overworld]},
	{name: "Repair an Item with a Grindstone", difficulty: 4, tags: [Action]},
	{name: "Give a Fox a Sword", difficulty: 12, tags: [Action, Overworld, RareBiome]},
	{name: "Open a Door with a Target Block from 10 blocks away", difficulty: 9, tooltiptext: "YOU have to be 10 blocks away, not the Target Block from the Door.", tooltipimg: "Goal Tooltip Images/TargetAndDoor.jpg",  tags: [Action, Overworld]},
	{name: "Barter with a Piglin", difficulty: 13, tags: [Action, Nether]},
	{name: "Remove an Enchantment with a Grindstone", difficulty: 12, tags: [Action]},
	{name: "Clean a Pattern off a Banner", difficulty: 11, tags: [Action, Overworld]},
	{name: "Tame a Horse", difficulty: 4, tags: [Action, Overworld]},
	{name: "Empty a Cauldron without Buckets or Bottles", difficulty: 5, tooltiptext: "You can fill the Cauldron with Water however you want, just don't use Buckets or Bottles to empty it.", tags: [Action, Overworld]},
	{name: "Sleep in a Villager's bed", difficulty: 4, reactant: ["Sleep"], tags: [Action, Village, Overworld]},
	{name: "Set fire to a Villager's House", difficulty: 7, tags: [Action, Village, Overworld]},
	{name: "Place an Iron, Gold and Diamond block on top of each other", difficulty: 18, tags: [Build, Ore]},
	{name: "Wear 4 Different Armour types at the same time", difficulty: 18, tooltiptext: "Example: GOLD shoes, LEATHER Trousers, IRON Chestplate and DIAMOND Helmet.", tooltipimg: "Goal Tooltip Images/4Armour.jpg", reactant: ["WearArmour"], tags: [Action]},
	{name: "Fill a Hopper with 320 items", difficulty: 10, tags: [Action, Item]},
	{name: "Place a Cactus in a Flower Pot", difficulty: 12, tags: [Action, RareBiome, Overworld]},
	{name: "Detonate a TNT-Minecart", difficulty: 11, tags: [Action, Overworld]},
	{name: "Tame a Wolf", difficulty: 10, tags: [Action, Overworld]},
	{name: "Create an Iron Golem", difficulty: 12, tags: [Action, Overworld]},
	{name: "Finish by jumping from top to bottom of the world", difficulty: 15, tooltiptext: "Dig a hole to Bedrock, build to Y=320 (height limit), then jump from top to bottom at the end of the Bingo.", tooltipimg: "Goal Tooltip Images/FinishTopToBottom.jpg", tags: [Action, Build, Overworld, Finish]},
	{name: "Die to your own arrow", difficulty: 8, reactant: ["Pacifist"], tags: [Action]},
	{name: "Get a '... whilst trying to escape ...' Death message", difficulty: 14, tooltiptext: "Example: 'PLAYER' drowned whilst trying to escape a Skeleton.", tags: [Action]},
	{name: "Finish on top of the world", difficulty: 12, tooltiptext: "Build up to Y=320 (height limit) and stand on the top at the end of the Bingo.", tooltipimg: "Goal Tooltip Images/FinishTop.jpg", tags: [Action, Build, Overworld, Finish]},
	{name: "Kill a hostile mob with Gravel", difficulty: 13, reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat]},
	{name: "Kill a hostile mob with Sand", difficulty: 14, reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat, Overworld]},
	{name: "Put a Carpet on a Llama", difficulty: 14, tags: [RareBiome, Action, Overworld]},
	{name: "Activate a (4-6)x(4-6) Nether Portal (not counting corners)", difficulty: 12, tooltiptext: "Width/height of the Obsidian frame, disregarding corners (or in other words, width/height of the—once activated—purple portal area).", tooltipimg: "Goal Tooltip Images/Portal.jpg", tags: [Action, Build, Nether]},
	{name: "Power a Redstone Lamp", difficulty: 12, tags: [Action, Overworld]},
	{name: "Kill a hostile mob with an Anvil", difficulty: 16, reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Use a Lead on a Rabbit", difficulty: 12, tags: [Action, Overworld]},
	{name: "Hang a mob with a Lead", difficulty: 5, reactant: ["Pacifist"], tooltiptext: "Suspend a mob in mid air using Fences and a Lead.", tooltipimg: "Goal Tooltip Images/HangingLead.jpg", tags: [Action, Overworld]},
	{name: "Deplete an Iron Sword", difficulty: 10, reactant: ["SwordUse"], tooltiptext: "Use an Iron Sword until it breaks, check the 'Items' statistics screen!", tooltipimg: "Goal Tooltip Images/SwordDepelete.jpg", tags: [Action, Stat]},
	{name: "Give a mob a Hat", difficulty: 13, tooltiptext: "This is impossible on Easy in game difficulty, and easier on Hard than Medium.", tags: [Action, Combat]},
	{name: "Add a Marker to a Map", difficulty: 11, tags: [Action, Overworld]},
	{name: "Leash a Dolphin to a Fence", difficulty: 7, tags: [Action, Ocean, Overworld]},
	{name: "Enchant an item", difficulty: 20, antisynergy: ["Enchant"], tags: [Action, Overworld]},
	{name: "Tame a Cat", difficulty: 8, tags: [Action, Village, Overworld]},
	{name: "Kill an Iron Golem", difficulty: 13, reactant: ["Pacifist"], tags: [Action, Overworld]},
	{name: "Kill a mob with an End Crystal", difficulty: 44, reactant: ["Pacifist"], tags: [Action, Overworld, Nether, Combat]},
	{name: "Light a Campfire from 10 blocks away", difficulty: 9, tags: [Action]},
	{name: "Ignite a TNT with a Lectern", difficulty: 16, tags: [Action, Overworld]},
	{name: "Kill a hostile mob with a Sweet Berry Bush", difficulty: 20, reactant: ["Pacifist"], tags: [Action, Overworld, Combat, RareBiome]},
	{name: "Gain a Fox's Trust", difficulty: 15, tags: [Action, Overworld, RareBiome]},
	{name: "Repair an Iron Golem", difficulty: 10, tags: [Action, Overworld, Village]},
	{name: "(Try to) use a Respawn Anchor in the Overworld", difficulty: 24, tags: [Action, Nether]},
	{name: "Convert a Hoglin into a Zoglin", difficulty: 23, tags: [Action, Nether, Combat]},
	{name: "Ride a Strider", difficulty: 18, tags: [Action, Nether]},
	{name: "Damage a Strider with Water", difficulty: 25, tags: [Action, Nether]},
	{name: "Die to using an Ender Pearl", difficulty: 9, tooltiptext: "Need to die to the damage taken from using a Pearl.", tooltipimg: "Goal Tooltip Images/EnderPearl.jpg", reactant: ["Pacifist"], tags: [Action]},
	{name: "Bounce on a Slime Block", difficulty: 13, tooltiptext: "Get a Slime Block, place it on the ground and give it a good old bouncin' on.", tooltipimg: "Goal Tooltip Images/SlimeBlock.jpg", tags: [Action, Overworld]},
	{name: "Grow a Huge Nether Fungus", difficulty: 12, antisynergy: ["GrowFungus"], tags: [Action, Nether]},
	{name: "Put a Chest on a Donkey", difficulty: 16, tags: [Action, Overworld]},
	{name: "Grow a Tree with a Bee Nest attached", difficulty: 24, tags: [Action, Overworld]},
	{name: "Dig straight down to Bedrock from Sea level (1x1 hole)", difficulty: 12, tooltiptext: "Sea Level is Y=63, but starting from higher is fine.", tags: [Action, Overworld]},
	//#endregion

	//#region Mobs (Friend and Foe)
	{name: "(5-10) Rotten Flesh", difficulty: 4, infrequency: 3, tags: [Item]},
	{name: "(11-20) Rotten Flesh", difficulty: 6, infrequency: 3, tags: [Item]},
	{name: "(21-32) Rotten Flesh", difficulty: 8, infrequency: 3, tags: [Item]},
	{name: "(33-48) Rotten Flesh", difficulty: 12, infrequency: 3, tags: [Item]},
	{name: "(49-64) Rotten Flesh", difficulty: 16, infrequency: 3, tags: [Item]},
	{name: "Feather", difficulty: 1, antisynergy: ["Feathers"], infrequency: 5, tags: [Item]},
	{name: "(3-8) Feathers", difficulty: 2, antisynergy: ["Feathers"], infrequency: 5, tags: [Item]},
	{name: "(9-16) Feathers", difficulty: 3, antisynergy: ["Feathers"], infrequency: 5, tags: [Item]},
	{name: "(16-24) Feathers", difficulty: 4, antisynergy: ["Feathers"], infrequency: 5, tags: [Item]},
	{name: "(25-32) Feathers", difficulty: 5, antisynergy: ["Feathers"], infrequency: 5, tags: [Item]},
	{name: "(5-8) Ink Sacs", difficulty: 4, antisynergy: ["InkSacs"], infrequency: 3, tags: [Item, Overworld]},
	{name: "(9-16) Ink Sacs", difficulty: 6, antisynergy: ["InkSacs"], infrequency: 3, tags: [Item, Overworld]},
	{name: "(17-32) Ink Sacs", difficulty: 9, antisynergy: ["InkSacs"], infrequency: 3, tags: [Item, Overworld]},
	{name: "Fermented Spider Eye", difficulty: 10, tags: [Item, Overworld]}, // 5 + 3 + 2
	{name: "(2-3) Ender Pearls", difficulty: 9, infrequency: 2, tags: [Item]},
	{name: "(4-6) Ender Pearls", difficulty: 11, antisynergy: ["EnderPearl"], infrequency: 2, tags: [Item, Combat]},
	{name: "Chicken Egg", difficulty: 3, antisynergy: ["ChickenEggs"], tags: [Item]},
	{name: "16 Chicken Eggs", difficulty: 9, antisynergy: ["ChickenEggs"], tags: [Item]},
	{name: "Hatch a Chicken from an Egg", difficulty: 8, tags: [Action, Overworld]},
	{name: "(4-6) Bone Blocks", difficulty: 9, tags: [Item]},
	{name: "Drown a Zombie", difficulty: 7, tags: [Action, Combat, Overworld]},
	{name: "Gunpowder", difficulty: 5, infrequency: 3, tags: [Item]},
	{name: "(3-5) Gunpowder", difficulty: 6, infrequency: 3, tags: [Item]},
	{name: "(6-10) Gunpowder", difficulty: 8, infrequency: 3, tags: [Item, Combat]},
	{name: "(11-16) Gunpowder", difficulty: 10, infrequency: 3, tags: [Item, Combat]},
	{name: "(17-32) Gunpowder", difficulty: 14, infrequency: 3, tags: [Item, Combat]},
	{name: "(2-5) Spider Eyes", difficulty: 5, infrequency: 2, tags: [Item, Overworld]},
	{name: "(6-12) Spider Eyes", difficulty: 7, infrequency: 2, tags: [Item, Combat, Overworld]},
	{name: "Kill (3-6) passive mobs with only fire", difficulty: 7, tooltiptext: "Don't hurt the passive mob any other way, only with Fire.", reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Kill a Creeper with only fire", difficulty: 9, reactant: ["Pacifist"], tags: [Action, Combat, Overworld]},
	{name: "Rotten Flesh, Spider Eye, Bone, Gunpowder and Ender Pearl", difficulty: 11, tags: [Item, Combat, Overworld]},
	{name: "Place a Fish in the Nether", difficulty: 10, reactant: ["Pacifist"], tags: [Nether, Action, Overworld]},
	{name: "Honey Bottle", difficulty: 14, antisynergy: ["Honey"], infrequency: 2, tags: [Item, Overworld]},
	{name: "3 Honeycombs", difficulty: 14, antisynergy: ["Honeycomb"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Honey Block", difficulty: 24, antisynergy: ["Honey"], infrequency: 2, tags: [Action, Overworld]},
	{name: "3 Honeycomb Blocks", difficulty: 24, antisynergy: ["Honeycomb"], infrequency: 2, tags: [Action, Overworld]},
	{name: "(2-3) Honey Blocks", difficulty: 34, antisynergy: ["Honey"], infrequency: 2, tags: [Action, Overworld]},
	{name: "(6-12) Honeycomb Blocks", difficulty: 34, antisynergy: ["Honeycomb"], infrequency: 2, tags: [Action, Overworld]},
	{name: "Get a Skeleton's Bow", difficulty: 10, reactant: ["Pacifist"], tooltiptext: "Kill Skeletons until you get the rare Bow drop from one.", tags: [Item, Combat]},
	{name: "(5-9) Slimeballs", difficulty: 15, tags: [Item, RareBiome, Overworld]},
	{name: "Phantom Membrane", difficulty: 40, reactant: ["Pacifist"], tags: [Item, Combat, Overworld]},
	{name: "Get a Pillager's Crossbow", difficulty: 18, reactant: ["Pacifist"], tooltiptext: "Kill Pillagers until you get a rare Crossbow drop from one.", tags: [Item, Combat, Overworld, RareBiome]},
	{name: "Ominous Banner", difficulty: 16, reactant: ["Pacifist"], tags: [Item, Combat, Overworld]},
	{name: "Brown Wool", difficulty: 11, tags: [Item, Overworld]},
	{name: "Scute", difficulty: 40, antisynergy: ["TurtleShell"], tags: [Item, Ocean, Overworld]},
	//#endregion

	//#region Ocean
	{name: "(32-64) Kelp", difficulty: 5, tags: [Item, Ocean, Overworld, Food]},
	{name: "(11-20) Dried Kelp Blocks", difficulty: 6, infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(21-32) Dried Kelp Blocks", difficulty: 7, infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Tropical Fish", difficulty: 4, tags: [Item, Ocean, Overworld]},
	{name: "Pufferfish", difficulty: 4, antisynergy: ["Pufferfish"], tags: [Item, Ocean, Overworld]},
	{name: "(15-32) Seagrass", difficulty: 7, infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(33-64) Seagrass", difficulty: 8, infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(2-3) Prismarine Crystals", difficulty: 8, infrequency: 2, tags: [Item, Ocean, Overworld]},
	//#endregion

	//#region Food
	{name: "(2-5) Bread", difficulty: 5, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(6-16) Bread", difficulty: 6, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "Apple", difficulty: 5, antisynergy: ["Apples"], tags: [Item, Overworld, Food]},
	{name: "(2-5) Apples", difficulty: 6, antisynergy: ["Apples"], tags: [Item, Overworld]},
	{name: "(2-6) Raw Cod", difficulty: 2, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(7-16) Raw Cod", difficulty: 3, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(2-6) Raw Salmon", difficulty: 2, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(7-16) Raw Salmon", difficulty: 3, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(2-3) Different Edible Items", difficulty: 3, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", infrequency: 2, tags: [Item, Food]}, // not tagged with Overworld, because you can get 3 in the Nether
	{name: "(4-5) Different Edible Items", difficulty: 6, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(6-7) Different Edible Items", difficulty: 12, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "3 Different Fish", difficulty: 6, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Cod and Cooked Cod).", tags: [Item, Overworld, Food]},
	{name: "Mushroom Stew", difficulty: 10, tags: [Item, Food]},
	{name: "Eat an entire Cake", difficulty: 13, reactant: ["EatNonMeat"], tags: [Action, Overworld, Food]}, // 4 + 1 + 3 + 5
	{name: "Pumpkin Pie", difficulty: 8, tags: [Item, Overworld, Food]}, // 4 + 3 + 1
	{name: "Golden Apple", difficulty: 10, tags: [Item, Food]},
	{name: "Golden Carrot", difficulty: 12, tags: [Item, Food]},
	{name: "(2-6) Sweet Berries", difficulty: 10, tags: [Item, Overworld, RareBiome, Food]},
	{name: "Drink a Suspicious Stew", difficulty: 10, reactant: ["EatNonMeat"], tags: [Item, Overworld, Food]},
	{name: "Beetroot Soup", difficulty: 12, tags: [Item, Overworld, Food]},
	{name: "(16-32) Melon Slices", difficulty: 20, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "(33-64) Melon Slices", difficulty: 21, infrequency: 2, tags: [Item, Overworld, Food]},
	{name: "Rabbit Stew", difficulty: 14, tags: [Item, Overworld, Food]},
	//#endregion
	
	//#region Never
	{name: "Never Pick up Crafting Tables", difficulty: 2, tooltiptext: "Never break and pick up Crafting Tables. You can make, place and use, but not collect.", tags: [Never]},
	{name: "Never use a Fishing Rod", difficulty: 1, tooltiptext: "You can use Fishing Rods in crafting, but cannot use them for casting and reeling", catalyst: ["Fishing"], tags: [Never, Overworld]},
	{name: "Never Sleep", difficulty: 13, catalyst: ["Sleep"], tags: [Never, Overworld]},
	{name: "Never wear Chestplates", difficulty: 4, catalyst: ["WearArmour"], antisynergy: ["NeverWearArmour"], tags: [Never]},
	{name: "Never use Shields", difficulty: 8, tooltiptext: "You can use Shields in crafting, but cannot use them for blocking", tags: [Never]},
	{name: "Never use a Boat", difficulty: 6, tags: [Never, Overworld]},
	{name: "Never use Debug (F3)", difficulty: 14, tags: [Never]},
	{name: "Never use a Sword", difficulty: 4, catalyst: ["SwordUse"], tooltiptext: "Never use a Sword for Combat or Block Breaking. Holding or crafting is fine.", tooltipimg: "Goal Tooltip Images/NoSword.jpg", tags: [Never]},
	{name: "Carnivore", difficulty: 8, tooltiptext: "Only eat meat.", tooltipimg: "Goal Tooltip Images/NoBread.jpg", antisynergy: ["Food"], tags: [Never, Action], catalyst: ["EatNonMeat"]},
	{name: "Vegetarian", difficulty: 10, tooltiptext: "Never eat meat, including fish.", tooltipimg: "Goal Tooltip Images/NoFish.jpg", antisynergy: ["Food"], tags: [Never, Action], catalyst: ["EatMeat"]},
	{name: "Never wear any Armour", difficulty: 12, catalyst: ["WearArmour"], antisynergy: ["NeverWearArmour"], tags: [Never]},
	{name: "Never use Coal", difficulty: 6, tooltiptext: "Never use Coal for any crafting recipes or fuel in a Furnace, CAN use Charcoal.", catalyst: ["NeverCoal"], tooltipimg: "Goal Tooltip Images/NoCoal.jpg", tags: [Never]},
	{name: "Never use an Axe", difficulty: 10, catalyst: ["AxeUse"], tags: [Never]},
	{name: "Never Craft Sticks", difficulty: 12, tags: [Never, Overworld]}, // Overworld because can't get sticks in the Nether without crafting them
	{name: "Never place Torches", difficulty: 6, tooltiptext: "Never place normal Torches, you CAN craft with them. Other types of Torches are allowed.", tags: [Never]},
	{name: "Never wear Armour or use Shields", difficulty: 20, tooltiptext: "You can use Armour/Shields in crafting, but cannot wear the Armour or block with Shields", catalyst: ["WearArmour"], antisynergy: ["NeverWearArmour"], tags: [Never]},
	{name: "Never use Buckets", difficulty: 14, catalyst: ["UseBuckets"], tags: [Never]},
	{name: "Pacifist", difficulty: 30, tooltiptext: "Never kill any creature, as per the statistics screen", catalyst: ["Pacifist"], tags: [Never, Stat]},
	{name: "Never smelt with Furnaces", difficulty: 18, tooltiptext: "You can use Furnaces in crafting, but cannot use them for cooking or smelting", catalyst: ["UseFurnace"], tags: [Never]},
	//#endregion

	//#region Sand
	{name: "(8-16) Sand", difficulty: 1, infrequency: 4, tags: [Item, Overworld]},
	{name: "(17-32) Sand", difficulty: 2, infrequency: 4, tags: [Item, Overworld]},
	{name: "(33-48) Sand", difficulty: 3, infrequency: 4, tags: [Item, Overworld]},
	{name: "(49-64) Sand", difficulty: 4, infrequency: 4, tags: [Item, Overworld]},
	{name: "(8-16) Sandstone", difficulty: 2, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(17-32) Sandstone", difficulty: 3, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(33-48) Sandstone", difficulty: 4, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(49-64) Sandstone", difficulty: 5, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(8-16) Cut Sandstone", difficulty: 2, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(17-32) Cut Sandstone", difficulty: 3, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(33-48) Cut Sandstone", difficulty: 4, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	{name: "(49-64) Cut Sandstone", difficulty: 5, antisynergy: ["Sandstone"], infrequency: 4, tags: [Item, Overworld]},
	//#endregion

	//#region Nether
	{name: "(9-16) Nether Brick Blocks", difficulty: 10, infrequency: 4, tags: [Item, Nether]},
	{name: "(17-32) Nether Brick Blocks", difficulty: 11, infrequency: 4, tags: [Item, Nether]},
	{name: "(33-48) Nether Brick Blocks", difficulty: 12, infrequency: 4, tags: [Item, Nether]},
	{name: "(49-64) Nether Brick Blocks", difficulty: 13, infrequency: 4, tags: [Item, Nether]},
	{name: "(2-10) Red Nether Brick Blocks", difficulty: 15, infrequency: 4, tags: [Item, Nether]},
	{name: "(11-20) Red Nether Brick Blocks", difficulty: 16, infrequency: 4, tags: [Item, Nether]},
	{name: "(21-32) Red Nether Brick Blocks", difficulty: 17, infrequency: 4, tags: [Item, Nether]},
	{name: "Grow a Tree in the Nether", difficulty: 11, tooltiptext: "Huge Crimson/Warped Fungi don't count.", tags: [Action, Nether, Overworld]},
	{name: "(5-16) Soul Sand", difficulty: 12, tags: [Item, Nether]}, // Soul sand can be found in anchient cities, but that's dumb
	{name: "(5-16) Soul Soil", difficulty: 14, tags: [Item, Nether]},
	{name: "(Try to) Sleep in the Nether", difficulty: 14, tags: [Action, Nether, Overworld]},
	{name: "(2-6) Basalt", difficulty: 12, tags: [Item, Nether]},
	{name: "(2-6) Blackstone", difficulty: 11, tags: [Item, Nether]},
	{name: "Fill all 4 slots of a Soul Campfire with Porkchops", difficulty: 14, reactant: ["Pacifist"], tags: [Action, Nether, Combat]}, // Soul sand can be found in anchient cities, but that's dumb
	{name: "Soul Lantern", difficulty: 12, tags: [Item, Nether]}, // Soul sand can be found in anchient cities, but that's dumb
	{name: "Potion of Fire Resistance", difficulty: 14, infrequency: 12, tags: [Item, Nether]}, // no Pacifist reactant and no Combat tag (Blaze Powder), no Overworld tag (Water Bottles), because can be bartered
	{name: "Potion of Healing", difficulty: 20, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Poison", difficulty: 18, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Harming", difficulty: 22, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Regeneration", difficulty: 22, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Slowness", difficulty: 22, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Strength", difficulty: 18, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Swiftness", difficulty: 18, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Weakness", difficulty: 20, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Leaping", difficulty: 20, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, RareBiome, Overworld, Combat]},
	{name: "Potion of Slow Falling", difficulty: 44, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Combat, Overworld]},
	{name: "Potion of the Turtle Master", difficulty: 62, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Ocean, Overworld, Combat]},
	{name: "(16-32) Spectral Arrows", difficulty: 12, tags: [Item, Nether]},
	{name: "(16-32) Glowstone Dust", difficulty: 12, infrequency: 2, tags: [Item, Nether]},
	{name: "(33-64) Glowstone Dust", difficulty: 14, infrequency: 2, tags: [Item, Nether]},
	{name: "(2-3) Magma Cream", difficulty: 16, tags: [Item, Nether, Combat]},
	{name: "Eye of Ender", difficulty: 22, reactant: ["Pacifist"], antisynergy: ["EyeOfEnder"], tags: [Item, Nether, Combat]},
	{name: "Daylight Detector", difficulty: 12, tags: [Item, Overworld, Nether]},
	{name: "Blaze Rod", difficulty: 18, reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Ghast Tear", difficulty: 17, reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Block of Quartz", difficulty: 12, tags: [Item, Nether]},
	{name: "Warped Fungus on a Stick", difficulty: 12, tags: [Item, Nether, Tool]},
	//#endregion 
	
	//#region Colour
	{name: "(2-4) Colours of Wool", difficulty: 2, infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(5-8) Colours of Wool", difficulty: 8, infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(8-11) Colours of Wool", difficulty: 16, infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(12-14) Colours of Wool", difficulty: 24, infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(4-7) Colours of Terracotta", difficulty: 8, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 3, tags: [Item, Colour, Overworld]},
	{name: "(7-10) Colours of Terracotta", difficulty: 16, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 3, tags: [Item, Colour, Overworld]},
	{name: "(11-13) Colours of Terracotta", difficulty: 24, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 3, tags: [Item, Colour, Overworld]},
	{name: "(4-7) Colours of Glazed Terracotta", difficulty: 9, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 3, tags: [Item, Colour, Overworld]},
	{name: "(7-10) Colours of Glazed Terracotta", difficulty: 17, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 3, tags: [Item, Colour, Overworld]},
	{name: "(11-13) Colours of Glazed Terracotta", difficulty: 25, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 3, tags: [Item, Colour, Overworld]},
	{name: "(2-3) Different Coloured Shields", difficulty: 6, tags: [Item, Colour, Overworld]},
	{name: "Blue Dye", difficulty: 3, infrequency: 10, tags: [Item, Overworld]},
	{name: "Light Blue Dye", difficulty: 3, infrequency: 10, tags: [Item, Overworld]},
	{name: "Cyan Dye", difficulty: 13, infrequency: 10, tags: [Item, Overworld]}, // 3 + 10
	{name: "Magenta Dye", difficulty: 6, infrequency: 10, tags: [Item, Overworld]},
	{name: "Red Dye", difficulty: 1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Orange Dye", difficulty: 2, infrequency: 10, tags: [Item, Overworld]},
	{name: "Yellow Dye", difficulty: 1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Green Dye", difficulty: 10, reactant: ["UseFurnace"], infrequency: 10, tags: [Item, RareBiome, Overworld]},
	{name: "Pink Dye", difficulty: 2, infrequency: 10, tags: [Item, Overworld]},
	{name: "Purple Dye", difficulty: 2, infrequency: 10, tags: [Item, Overworld]},
	{name: "Lime Dye", difficulty: 10, reactant: ["UseFurnace"], infrequency: 10, tags: [Item, Overworld]},
	{name: "Brown Dye", difficulty: 20, infrequency: 10, tags: [Item, Overworld]},
	{name: "Wear 4 different colour Leather Armour at the same time", difficulty: 7, reactant: ["WearArmour"], tags: [Item, Colour, Overworld]},
	{name: "(3-6) Colours of Concrete", difficulty: 8, antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (3-6) colours of Beds next to each other", difficulty: 8, antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "(7-10) Colours of Concrete", difficulty: 17, antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (7-10) colours of Beds next to each other", difficulty: 17, antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Finish by launching Fireworks of (5-7) Different Colours", difficulty: 20, tags: [Action, Item, Colour, Overworld, Finish]},
	{name: "(11-14) Colours of Concrete", difficulty: 26, antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (11-14) colours of Beds next to each other", difficulty: 26, antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	//#endregion

	// #region Unsorted
	{name: "Note Block", difficulty: 6, tags: [Item, Overworld]},
	{name: "16 Snowballs", difficulty: 10, tags: [Item, RareBiome, Overworld]},
	{name: "(2-4) Different Slabs", difficulty: 3, infrequency: 2, tags: [Item]},
	{name: "(5-7) Different Slabs", difficulty: 8, infrequency: 2, tags: [Item]},
	{name: "(2-4) Different Stairs", difficulty: 3, infrequency: 2, tags: [Item]},
	{name: "(5-7) Different Stairs", difficulty: 8, infrequency: 2, tags: [Item]},
	{name: "Hay Bale", difficulty: 5, tags: [Item, Overworld]},
	{name: "Flower Pot", difficulty: 2, tags: [Item, Overworld]},
	{name: "(5-16) Charcoal", difficulty: 3, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(2-4) Different Gold Items", difficulty: 5, tooltiptext: "Any item with 'Gold' in its name (yes, even Raw and Ingots).", tags: [Item]},
	{name: "(5-7) Different Gold Items", difficulty: 7, tooltiptext: "Any item with 'Gold' in its name (yes, even Ingots and Ores).", tags: [Item]},
	{name: "(3-4) Different Diamond Items", difficulty: 10, tooltiptext: "Any item with 'Diamond' in its name (yes, even itself).", tags: [Item]},
	{name: "(5-7) Different Diamond Items", difficulty: 14, tooltiptext: "Any item with 'Diamond' in its name (yes, even itself).", tags: [Item]},
	{name: "(2-5) Paper", difficulty: 3, infrequency: 2, tags: [Item, Overworld]},
	{name: "(6-16) Paper", difficulty: 4, infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-4) Flint", difficulty: 2, infrequency: 6, tags: [Item]},
	{name: "(5-8) Flint", difficulty: 3, infrequency: 6, tags: [Item]},
	{name: "(9-16) Flint", difficulty: 4, infrequency: 6, tags: [Item]},
	{name: "(17-36) Flint", difficulty: 5, infrequency: 6, tags: [Item]},
	{name: "(33-48) Flint", difficulty: 6, infrequency: 6, tags: [Item]},
	{name: "(49-64) Flint", difficulty: 7, infrequency: 6, tags: [Item]},
	{name: "Book and Quill", difficulty: 8, tags: [Item, Overworld]},
	{name: "(2-4) Bookshelves", difficulty: 5, tags: [Item, Overworld]},
	{name: "Jukebox", difficulty: 9, tags: [Item]},
	{name: "(2-3) TNT", difficulty: 10, tags: [Item, Overworld]},
	{name: "Full Iron Armour", difficulty: 8, infrequency: 3, tags: [Item]},
	{name: "Full Leather Armour", difficulty: 8, infrequency: 3, tags: [Item]},
	{name: "(16-32) Brick Blocks", difficulty: 8, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "Banner Pattern", difficulty: 6, tooltiptext: "Any kind of Banner Pattern.", tags: [Item, Overworld]},
	{name: "Become Nauseous", difficulty: 5, antisynergy: ["Pufferfish"], reactant: ["EatMeat"], tags: [Item, Ocean, Overworld]},
	{name: "Enchanted item", difficulty: 8, tags: [Item]},
	{name: "(5-10) Magma Blocks", difficulty: 9, infrequency: 3, tags: [Item]},
	{name: "(11-20) Magma Blocks", difficulty: 11, infrequency: 3, tags: [Item]},
	{name: "(21-32) Magma Blocks", difficulty: 13, infrequency: 3, tags: [Item]},
	{name: "Damaged Anvil", difficulty: 12, tags: [Item]},
	{name: "6 Fire Charges", difficulty: 17, tags: [Item]}, // No nether/combat tag coz can find in ruined portals and trial chambers, 16 coz you don't *NEED* Blaze rods if round in chests
	{name: "(2-4) Obsidian", difficulty: 11, infrequency: 2, tags: [Item]},
	{name: "(5-10) Obsidian", difficulty: 13, infrequency: 2, tags: [Item]},
	{name: "Firework Star", difficulty: 6, tags: [Item, Overworld]},
	{name: "(16-32) Item Frames", difficulty: 9, tags: [Item]},
	{name: "Saddle", difficulty: 5, tags: [Item]},
	{name: "Heart of the Sea", difficulty: 10, tags: [Item, Ocean, Overworld]},
	{name: "Max Scale Map", difficulty: 12, tooltiptext: "You don't need to complete it, just zoom it out to the max.", tags: [Item, Overworld]},
	{name: "Crying Obsidian", difficulty: 17, tags: [Item]},
	{name: "Full Gold Armour", difficulty: 10, tags: [Item]},
	//#endregion

	// Hard (3)
	{name: "Create an Enchantment requiring level 10+", difficulty: 30, tags: [Action, Overworld]},
	{name: "Milk a Mooshroom", difficulty: 40, antisynergy: ["Mooshroom"], infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Shear a Mooshroom", difficulty: 40, antisynergy: ["Mooshroom"], infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Sea Lantern", difficulty: 16, antisynergy: ["SeaLantern"], infrequency: 3, tags: [Item, Combat, Ocean, Overworld]},
	{name: "(2-4) Sea Lanterns", difficulty: 20, antisynergy: ["SeaLantern"], infrequency: 3, tags: [Item, Combat, Ocean, Overworld]},
	{name: "(5-10) Sea Lanterns", difficulty: 25, antisynergy: ["SeaLantern"], infrequency: 3, tags: [Item, Combat, Ocean, Overworld]},
	{name: "(11-16) Sea Lanterns", difficulty: 30, antisynergy: ["SeaLantern"], infrequency: 3, tags: [Item, Combat, Ocean, Overworld]},
	{name: "Sponge", difficulty: 20, tooltiptext: "DRY Sponge, not a Wet one", tooltipimg: "Goal Tooltip Images/Sponge.jpg", tags: [Item, Combat, Ocean, Overworld]},
	{name: "Listen to an entire Music Disc", difficulty: 26, tooltiptext: "It doesn't count until the song naturally finishes!", tags: [Action]},


	{name: "Get a Zombified Piglin's Sword", difficulty: 23, reactant: ["Pacifist"], tooltiptext: "Kill Zombified Piglins until you get a rare drop from one, it being their Golden Sword.", tooltipimg: "Goal Tooltip Images/GoldenSword.jpg", tags: [Action, Combat, Nether]},

	{name: "Nametag an Enderman", difficulty: 24, tags: [Action, Combat, Overworld]},
	{name: "Nametag a Wither", difficulty: 120, reactant: ["Pacifist"], tags: [Action, Combat, Overworld]},
	{name: "Finish on top of a Blaze Spawner", difficulty: 18, tooltiptext: "Be stood on top of a Blaze Spawner at the end of the game.", tags: [Action, Nether, Combat, Finish]},
	



	{name: "Poison a Parrot", difficulty: 24, reactant: ["Pacifist"], infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Tame a Parrot", difficulty: 24, infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Complete a dance with a Parrot", difficulty: 50, tooltiptext: "You also have to dance. It doesn't count until the music disc naturally finishes!", infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Ice Block on top of a Magma Block", difficulty: 20, tags: [Item, Build, Overworld]},

	{name: "Build a (2-4)x(2-4)x(2-4) Ice cube", difficulty: 24, tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/IceCube.jpg", tags: [Build, Overworld]},
	{name: "Finish on top of a stairway to Heaven", difficulty: 18, tooltiptext: "Using Stairs, build up to Y=320 (height limit) and stand on top at the end of the Bingo. (If you need to jump over a block, it's not a finished stairway.)", tooltipimg: "Goal Tooltip Images/FinishStairs.jpg", tags: [Build, Overworld, Finish]},
	{name: "Get a regular Ghast into the Overworld", difficulty: 30, tooltiptext: "Not the Happy Ghast.", tags: [Action, Nether, Overworld]},
	{name: "Enchanted Golden Apple", difficulty: 27, tags: [Item]},

	{name: "Kill a mob that is wearing Full Iron Armour", difficulty: 21, reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Enchant 5 different items", difficulty: 23, antisynergy: ["Enchant"], tags: [Action, Overworld]},

	{name: "Conduit", difficulty: 140, tags: [Item, Ocean, Overworld]},
	{name: "(2-5) types of Dead Coral Blocks", difficulty: 20, tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "Sea Pickle", difficulty: 16, infrequency: 3, tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "(2-8) Sea Pickles", difficulty: 18, infrequency: 3, tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "(9-16) Sea Pickles", difficulty: 20, infrequency: 3, tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "Get a '... didn't want to live in the same world as ...' Death message", difficulty: 52, tags: [Action, End]}, // This didn't have an End tag but surely? What are you gonna do, break bedrock real quick?
	{name: "Cookie", difficulty: 20, tags: [Item, Overworld]},
	{name: "Grow a Mega Jungle Tree", difficulty: 23, tooltiptext: "A mega tree is one grown with a 2x2 square of saplings.", tags: [Action, RareBiome, Overworld]},
	{name: "(2-5) Prismarine Shards", difficulty: 24, infrequency: 2, tags: [Item, Ocean, Overworld]},


	
	{name: "Destroy a Monster Spawner", difficulty: 18, tags: [Action, Combat]},
	{name: "(32-64) Popped Chorus Fruit", difficulty: 55, tags: [Item, End]},
	{name: "Get a Villager into The End", difficulty: 62, tags: [Action, End, Village]},
	{name: "(5-16) Dragon's Breath", difficulty: 52, tags: [Item, Combat, End]},
	{name: "Dragon Egg", difficulty: 55, tags: [Item, Combat, End]},
	{name: "Complete a full size Map", difficulty: 33, antisynergy: ["CompleteMap"], tags: [Action, Overworld]},
	{name: "Be killed by a Villager", difficulty: 25, tooltiptext: "Check the 'Mobs' statistics screen!", tags: [Village, Overworld, Stat, Combat]},
	{name: "Activate a Totem of Undying", difficulty: 30, tags: [Item, Overworld]},
	{name: "Every type of Sword", difficulty: -1, infrequency: 2, antisynergy: ["EverySword"], tooltiptext: "Wooden, Stone, Copper, Iron, Gold, Diamond and yes, even Netherite.", tags: [Item, Nether, Netherite]},
	{name: "Every type of Pickaxe", difficulty: -1, infrequency: 2, antisynergy: ["EveryPickaxe"], tooltiptext: "Wooden, Stone, Copper, Iron, Gold, Diamond and yes, even Netherite.", tags: [Item, Nether, Netherite]},

	{name: "Finish by building a Scaffolding tower, then removing it", difficulty: -1, tooltiptext: "Build a 1x1 Scaffolding Tower from Bedrock to Y=320 (height limit) and then knock it all down as the final goal.", tags: [Build, Overworld, Finish]},
	{name: "Feed a Panda a Cake", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Make two Pandas breed", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Disarm a Pillager", difficulty: -1, tooltiptext: "Get a Pillager to not be holding any Weapons", tags: [Action, Overworld, Combat, RareBiome]},
	{name: "Stun a Ravager", difficulty: -1, tags: [Action, Overworld, Combat, Village]},
	{name: "Become Hero of the Village", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld, Combat, Village]},
	{name: "Gain an Ocelot's Trust", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "12 Eyes of Ender", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "How good is your luck?", tags: [Item, Nether, Combat]},
	{name: "Netherite Ingot", difficulty: 25, tags: [Item, Nether, Netherite]},
	{name: "Wither Skull", difficulty: 40, reactant: ["Pacifist"], tags: [Item, Nether, Combat, RareBiome]},
	{name: "Gilded Blackstone", difficulty: -1, tags: [Item, Nether, RareBiome]},
	{name: "Make a Compass point to a Lodestone", difficulty: -1, tags: [Action, Nether, Netherite]},
	{name: "Give a Piglin Brute an Enchanted Axe", difficulty: -1, tags: [Action, Nether, Combat, RareBiome]},
	{name: "Build a 6x6 Scaffolding n Shape (not counting corners)", difficulty: -1, tooltiptext: "Width/height of the inside frame, disregarding corners.", tooltipimg: "Goal Tooltip Images/ScaffingN.jpg", tags: [Build, Overworld]},

	{name: "Kill a Wandering Trader", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld, Combat]},
	{name: "Cure a Zombie Villager", difficulty: -1, tags: [Action, Overworld]},
	{name: "Throw a Mending Book into Lava", difficulty: -1, tags: [Action]},

	{name: "Grow a Huge Nether Fungus in the Overworld", difficulty: -1, antisynergy: ["GrowFungus"], tags: [Action, Overworld, Nether]},
	{name: "(32-64) Dirt, Netherrack and End Stone", difficulty: -1, tags: [Item, Overworld, Nether, End]},
	{name: "Tame a Mule", difficulty: -1, tags: [Action, Overworld]},
	{name: "Convert a Carrot on a Stick into a Fishing Rod", difficulty: -1, tags: [Action, Overworld]},
	{name: "Skull Charge Banner Pattern", difficulty: -1, tags: [Item, Nether, Combat, RareBiome, Overworld]},
	{name: "Turtle Shell", difficulty: -1, antisynergy: ["TurtleShell"], tags: [Item, Ocean, Overworld]},

	// Very Hard (4)
	{name: "(5-7) Different Ores", difficulty: -1, tooltiptext: "Coal, Diamond, Emerald, Gold, Iron, Lapis Lazuli, Nether Quartz, Nether Gold and Redstone Ores are your choices.", tooltipimg: "Goal Tooltip Images/Ores.jpg", tags: [Item, Overworld]},
	{name: "(12-15) Different Potions", difficulty: -1, tooltiptext: "Splash, Lingering, Enhanced and Extended variants DON'T count!", reactant: ["Pacifist"], tags: [Item, Nether, Combat, Overworld]},
	{name: "Every type of Chestplate", difficulty: -1, tooltiptext: "Leather, Gold, Chainmail, Iron, Diamond and yes, even Netherite.", tooltipimg: "Goal Tooltip Images/chainmail chest.jpg", tags: [Item, Combat, Netherite]},
	{name: "Any mob head OTHER than a Wither Skeleton's", difficulty: -1, tooltiptext: "Dragon, Skeleton, Zombie or a Creeper Head. Wither Skeleton skulls do NOT count.", tags: [Item, Combat, Overworld]},
	{name: "Every colour of Dye", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["EveryColour"], infrequency: 2, tooltiptext: "Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!", tooltipimg: "Goal Tooltip Images/EveryColourOfDye.png", tags: [Item, Colour, Overworld]},

	//{name: "Fill a Double Chest with 3456 items", reactant: ["UseChests"], tags: [Item, Action]}, BOOOORRRRRRRINNG AND TOO EASY
	{name: "(16-32) Tipped Arrows", difficulty: -1, tags: [Item, Nether, Overworld]},
	{name: "Place 1 of each Mineral block on top of each other", difficulty: -1, tooltiptext: "Coal, Iron, Gold, Diamond, Redstone, Lapis, Emerald, Quartz and Netherite blocks.", tooltipimg: "Goal Tooltip Images/MineralBlocks.jpg", tags: [Item, Build, Overworld, Nether, Netherite]},
	{name: "Sleep in a Woodland Mansion", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "(10-32) Mycelium", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "5 types of Coral Blocks", difficulty: -1, tooltiptext: "The alive stuff, not the Dead Coral Blocks.", tooltipimg: "Goal Tooltip Images/CoralBlocks.jpg", tags: [Item, RareBiome, Ocean, Overworld]},
	{name: "(32-64) Blue Ice", difficulty: -1, tags: [Item, Overworld]},
	{name: "Fully power a Conduit", difficulty: -1, tags: [Item, Ocean, Build, Overworld]},
	{name: "Every item Diamonds are used to Craft", difficulty: -1, antisynergy: ["DiamondItems"], tooltiptext: "Block, Axe, Boots, Chestplate, Helmet, Hoe, Leggings, Pickaxe, Shovel, Sword, Enchantment Table, Firework Star and Jukebox.", tags: [Item]},
	{name: "Get a Shulker into the Overworld", difficulty: -1, tags: [Action, Combat, End, Overworld]},
	{name: "(5-10) Diamond Blocks", difficulty: -1, antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "Complete a full size Map in the End", difficulty: -1, antisynergy: ["CompleteMap"], tags: [Action, Overworld, End]},
	{name: "(32-64) Wither Roses", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Get a Slimeball from a Panda", difficulty: -1, tags: [Item, Overworld, RareBiome]},
	{name: "2 Blocks of Netherite", difficulty: -1, tags: [Item, Nether, Netherite]},
	{name: "Full Netherite Armour and Tools", difficulty: -1, tags: [Item, Nether, Netherite]},
	{name: "Convert a Pig into a Zombified Piglin", difficulty: -1, tags: [Action, Overworld]},
	{name: "Trident", difficulty: -1, tags: [Item, Ocean, Combat, Overworld]},
	{name: "Tame a Skeleton Horse", difficulty: -1, tags: [Action, Overworld]},
	{name: "Make every colour of Parrot dance at the same time", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Place every colour of Bed next to each other", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["EveryColour"], infrequency: 2, tooltiptext: "Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!", tooltipimg: "Goal Tooltip Images/EveryBed.jpg", tags: [Action, Colour, Overworld]},
	{name: "Kill an Enderman with only Endermites", difficulty: -1, tooltiptext: "Don't hurt the Enderman any other way, only with Endermites.", tags: [Action, Combat, End]},
	{name: "Get Regeneration from a Beacon", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
];
