// This is part of a version currently in development and may be changed at any time.

// Tags (these have not been touched as of v4 yet)
var Item = {name: "Item", max: [25, 25, 20, 20, 20], line: true},
Stat = {name: "Stat", max: [5, 5, 5, 5, 5], line: true},
Action = {name: "Action", max: [20, 20, 20, 20, 20], line: true},
Build = {name: "Build", max: [20, 20, 20, 20, 20], line: true},
// note, that on lower difficulties, RareBiome means "Specific Biome"
RareBiome = {name: "RareBiome", max: [0, 1, 2, 4, 6], line: true},
Ocean = {name: "Ocean", max: [5, 5, 5, 5, 5], line: true},
Village = {name: "Village", max: [0, 1, 2, 3, 4], line: true},
Colour = {name: "Colour", max: [2, 2, 2, 2, 2], line: true},
Never = {name: "Never", max: [3, 3, 3, 2, 1], line: false},
Combat = {name: "Combat", max: [5, 10, 20, 20, 20], line: true},
Overworld = {name: "Overworld", max: [25, 25, 24, 21, 18], line: true},
Nether = {name: "Nether", max: [0, 2, 5, 10, 15], line: true},
End = {name: "End", max: [0, 0, 0, 1, 5], line: true},
Finish = {name: "Finish", max: [1, 1, 1, 1, 1], line: true},
Netherite = {name: "Netherite", max: [0, 0, 0, 1, 3], line: true};

var bingoList_v5 = [

	// Very Easy (0)
	{name: "(32-64) Cobblestone", difficulty: -1, tags: [Item, Overworld]},
	{name: "(32-64) Dirt", difficulty: -1, tags: [Item, Overworld]},
	{name: "(32-64) Oak Wood Planks", difficulty: -1, antisynergy: ["OakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Spruce Wood Planks", difficulty: -1, antisynergy: ["SprucePlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Birch Wood Planks", difficulty: -1, antisynergy: ["BirchPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Dark Oak Wood Planks", difficulty: -1, antisynergy: ["DarkOakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(32-64) Acacia Wood Planks", difficulty: -1, antisynergy: ["AcaciaPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Oak Logs", difficulty: -1, antisynergy: ["OakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Spruce Logs", difficulty: -1, antisynergy: ["SpruceLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Birch Logs", difficulty: -1, antisynergy: ["BirchLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Dark Oak Logs", difficulty: -1, antisynergy: ["DarkOakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Acacia Logs", difficulty: -1, antisynergy: ["AcaciaLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "Redstone", difficulty: -1, antisynergy: ["Redstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Lava Bucket", difficulty: -1, antisynergy: ["LavaBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item]},
	{name: "Milk Bucket", difficulty: -1, antisynergy: ["MilkBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Overworld]},
	{name: "Water Bucket", difficulty: -1, antisynergy: ["WaterBucket"], reactant: ["UseBuckets"], infrequency: 4, tags: [Item, Overworld]},
	{name: "Bucket of Fish", difficulty: -1, antisynergy: ["FishBucket"], reactant: ["UseBuckets"], infrequency: 4, tooltiptext: "Can be any of the types of Fish.", tooltipimg: "Goal Tooltip Images/FishBucket.jpg", tags: [Item, Ocean, Overworld]},
	{name: "(16-32) Andesite", difficulty: -1, infrequency: 3, tags: [Item, Overworld]},
	{name: "(16-32) Granite", difficulty: -1, infrequency: 3, tags: [Item, Overworld]},
	{name: "(16-32) Diorite", difficulty: -1, infrequency: 3, tags: [Item, Overworld]},
	{name: "Iron Block", difficulty: -1, antisynergy: ["IronBlocks"], infrequency: 2, tags: [Item]},
	{name: "(5-25) Poppies & (5-25) Dandelions", difficulty: -1, tags: [Item, Overworld]},
	{name: "Level (5-7)", difficulty: -1, antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "(2-5) Note Blocks", difficulty: -1, antisynergy: ["NoteBlocks"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(32-64) Leaves", difficulty: -1, tags: [Item, Overworld]},
	{name: "Build a (2-4)x(2-4)x(2-4) leaf cube", difficulty: -1, tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/LeafCube.jpg", tags: [Build, Overworld]},
	{name: "(2-4) Colours of Wool", difficulty: -1, antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(8-16) Snowballs", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "(2-4) Different Slabs", difficulty: -1, antisynergy: ["Slabs"], infrequency: 2, tags: [Item]},
	{name: "(2-4) Different Stairs", difficulty: -1, antisynergy: ["Stairs"], infrequency: 2, tags: [Item]},
	{name: "Diamond", difficulty: -1, tags: [Item]},
	{name: "(5-15) Rotten Flesh", difficulty: -1, antisynergy: ["RotFlesh"], infrequency: 2, tags: [Item]},
	{name: "(10-32) Stone", difficulty: -1, tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", antisynergy: ["Stone"], infrequency: 2, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(2-5) Bread", difficulty: -1, antisynergy: ["Bread"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Hay Bale", difficulty: -1, antisynergy: ["HayBale"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Flower Pot", difficulty: -1, tags: [Item, Overworld]},
	{name: "(2-10) Feathers", difficulty: -1, antisynergy: ["Feathers"], infrequency: 2, tags: [Item]},
	{name: "Sleep in a Bed", difficulty: -1, reactant: ["Sleep"], tags: [Action, Overworld]},
	{name: "(5-15) Charcoal", difficulty: -1, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(5-15) Coal", difficulty: -1, tags: [Item]},
	{name: "Fishing Rod", difficulty: -1, tags: [Item]},
	{name: "Apple", difficulty: -1, antisynergy: ["Apples"], tags: [Item, Overworld]},
	{name: "(32-64) Sticks", difficulty: -1, antisynergy: ["Sticks"], infrequency: 2, tags: [Item]},
	{name: "(32-64) Kelp", difficulty: -1, tags: [Item, Ocean, Overworld]},
	{name: "(5-10) Oak Wood", difficulty: -1, antisynergy: ["OakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Spruce Wood", difficulty: -1, antisynergy: ["SpruceWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Birch Wood", difficulty: -1, antisynergy: ["BirchWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Dark Oak Wood", difficulty: -1, antisynergy: ["DarkOakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Acacia Wood", difficulty: -1, antisynergy: ["AcaciaWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Oak Wood", difficulty: -1, antisynergy: ["StrippedOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Spruce Wood", difficulty: -1, antisynergy: ["StrippedSpruceWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Birch Wood", difficulty: -1, antisynergy: ["StrippedBirchWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Dark Oak Wood", difficulty: -1, antisynergy: ["StrippedDarkOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-10) Stripped Acacia Wood", difficulty: -1, antisynergy: ["StrippedAcaciaWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Oak Logs", difficulty: -1, antisynergy: ["StrippedOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Spruce Logs", difficulty: -1, antisynergy: ["StrippedSpruceLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Birch Logs", difficulty: -1, antisynergy: ["StrippedBirchLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Dark Oak Logs", difficulty: -1, antisynergy: ["StrippedDarkOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(5-15) Stripped Acacia Logs", difficulty: -1, antisynergy: ["StrippedAcaciaLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(2-5) Raw Cod", difficulty: -1, antisynergy: ["RawCod"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(2-3) Raw Salmon", difficulty: -1, antisynergy: ["RawSalmon"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(2-3) Different Edible Items", difficulty: -1, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", antisynergy: ["EdibleItems"], infrequency: 2, tags: [Item]}, // not tagged with Overworld, because you can get 3 in the Nether
	{name: "Breed a set of mobs", difficulty: -1, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, Stat]},
	{name: "Crouch a distance of (50-100) meters", difficulty: -1, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Fill all 4 slots of a Campfire", difficulty: -1, tags: [Action]},
	{name: "Change the colour of text on a Sign", difficulty: -1, tags: [Action]},
	{name: "Extinguish a Campfire", difficulty: -1, tags: [Action]},
	{name: "Never Pick up Crafting Tables", difficulty: -1, tooltiptext: "Never break and pick up Crafting Tables. You can make, place and use, but not collect.", tags: [Never]},
	{name: "(2-4) Different Gold Items", difficulty: -1, antisynergy: ["GoldItems"], tooltiptext: "Any item with 'Gold' in its name (yes, even Ingots and Ores).", tags: [Item]},
	{name: "(10-32) Sand", difficulty: -1, antisynergy: ["Sand"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-10) Sandstone", difficulty: -1, antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-10) Cut Sandstone", difficulty: -1, antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-5) Paper", difficulty: -1, antisynergy: ["Paper"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Never use a Fishing Rod", difficulty: -1, tooltiptext: "You can use Fishing Rods in crafting, but cannot use them for casting and reeling", catalyst: ["Fishing"], tags: [Never, Overworld]},
	{name: "Deplete a Hoe", difficulty: -1, tooltiptext: "Use a Hoe until it breaks, check the 'Items' statistics screen!", tags: [Action, Stat]},
	{name: "Bounce on a Bed", difficulty: -1, tags: [Action, Overworld]},
	{name: "Hang up a Painting", difficulty: -1, antisynergy: ["Painting"], tags: [Action, Overworld]},
	{name: "Fill a Composter", difficulty: -1, tooltiptext: "Add stuff until you can get Bonemeal out!", tooltipimg: "Goal Tooltip Images/FullComposter.jpg", tags: [Action]},

	// Easy (1)
	{name: "(2-4) Different Fish", difficulty: -1, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Cod and Cooked Cod).", tags: [Item, Overworld]},
	{name: "Grow a Tree in the Nether", difficulty: -1, tooltiptext: "Huge Crimson/Warped Fungi don't count.", tags: [Action, Nether, Overworld]},
	{name: "(4-7) Colours of Terracotta", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(2-5) Mushroom Stew", difficulty: -1, tags: [Item]},
	{name: "Shoot a Button with an Arrow", difficulty: -1, tags: [Action]},
	{name: "Book and Quill", difficulty: -1, tags: [Item, Overworld]},
	{name: "(16-64) Flint", difficulty: -1, tags: [Item]},
	{name: "Eat an entire Cake", difficulty: -1, reactant: ["EatNonMeat"], tags: [Action, Overworld]},
	{name: "Pumpkin Pie", difficulty: -1, tags: [Item, Overworld]},
	{name: "Fish a Treasure and a Junk item", difficulty: -1, tooltiptext: "Treasure: Bow, Enchanted Book, Name Tag, Nautilus Shell, Saddle. Junk: Lily Pad, Bowl, Leather, Boots, Rotten Flesh, Stick, Water Bottle, Bone, Ink Sac, Tripwire Hook", reactant: ["Fishing"], tags: [Action, Overworld]},
	{name: "(16-64) Coarse Dirt", difficulty: -1, tags: [Item, Overworld]},
	{name: "(2-3) Clocks", difficulty: -1, tags: [Item, Overworld]},
	{name: "(2-4) Iron Blocks", difficulty: -1, antisynergy: ["IronBlocks"], infrequency: 2, tags: [Item]},
	{name: "Gold Block", difficulty: -1, antisynergy: ["GoldBlocks"], infrequency: 2, tags: [Item]},
	{name: "Golden Apple", difficulty: -1, tags: [Item]},
	{name: "(2-4) Bookshelves", difficulty: -1, tags: [Item, Overworld]},
	{name: "Never wear Chestplates", difficulty: -1, catalyst: ["WearArmour"], antisynergy: ["NeverWearArmour"], tags: [Never]},
	{name: "Never use Shields", difficulty: -1, tooltiptext: "You can use Shields in crafting, but cannot use them for blocking", tags: [Never]},
	{name: "Jukebox", difficulty: -1, tags: [Item]},
	{name: "Build a 3x3x3 Glass cube and fill the middle with Lava", difficulty: -1, tags: [Build, Overworld]},
	{name: "(16-32) Mossy Cobblestone", difficulty: -1, tags: [Item, Overworld]}, // not RareBiome, because can be found in a Plains Village
	{name: "(5-15) Cacti", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "(2-3) TNT", difficulty: -1, tags: [Item, Overworld]},
	{name: "Level (8-15)", difficulty: -1, antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "Create a Snow Golem", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "(5-15) Note Blocks", difficulty: -1, antisynergy: ["NoteBlocks"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-15) Ink Sacs", difficulty: -1, antisynergy: ["InkSacs"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(6-10) Bread", difficulty: -1, antisynergy: ["Bread"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-3) Hay Bales", difficulty: -1, antisynergy: ["HayBale"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-8) Colours of Wool", difficulty: -1, antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Piston", difficulty: -1, tags: [Item, Overworld]},
	{name: "Full Iron Armour", difficulty: -1, infrequency: 3, tags: [Item]},
	{name: "Full Leather Armour", difficulty: -1, infrequency: 3, tags: [Item]},
	{name: "Fill a Cauldron with Water", difficulty: -1, tags: [Overworld]},
	{name: "Complete a Map", difficulty: -1, antisynergy: ["CompleteMap"], tags: [Action, Overworld]},
	{name: "(5-10) Soul Sand", difficulty: -1, tags: [Item, Nether]},
	{name: "(5-10) Soul Soil", difficulty: -1, tags: [Item, Nether]},
	{name: "(5-10) Pumpkins", difficulty: -1, tags: [Item, Overworld]},
	{name: "(2-5) Carved Pumpkins", difficulty: -1, tags: [Item, Overworld]},
	{name: "(10-30) Vines", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "(5-7) Different Slabs", difficulty: -1, antisynergy: ["Slabs"], infrequency: 2, tags: [Item]},
	{name: "Wooden, Stone, Gold, Iron and Diamond Sword", difficulty: -1, infrequency: 2, antisynergy: ["EverySword"], tags: [Item]},
	{name: "Wooden, Stone, Gold, Iron and Diamond Pickaxe", difficulty: -1, infrequency: 2, antisynergy: ["EveryPickaxe"], tags: [Item]},
	{name: "(16-64) Brick Blocks", difficulty: -1, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "(16-32) Nether Brick Blocks", difficulty: -1, reactant: ["UseFurnace"], tags: [Item, Nether]},
	{name: "(16-64) Arrows", difficulty: -1, tags: [Item]},
	{name: "(Try to) Sleep in the Nether", difficulty: -1, tags: [Action, Nether, Overworld]},
	{name: "Fermented Spider Eye", difficulty: -1, tags: [Item, Overworld]},
	{name: "(5-7) Different Stairs", difficulty: -1, antisynergy: ["Stairs"], infrequency: 2, tags: [Item]},
	{name: "(2-3) Ender Pearls", difficulty: -1, antisynergy: ["EnderPearl"], infrequency: 2, tags: [Item]},
	{name: "16 Chicken Eggs", difficulty: -1, tags: [Item]},
	{name: "Hang up 3 Different 4x4 Paintings", difficulty: -1, antisynergy: ["Painting"], tags: [Action, Overworld]},
	{name: "(5-10) Bone Blocks", difficulty: -1, tags: [Item]},
	{name: "2 Creepers in the same Boat", difficulty: -1, tooltiptext: "The 2 Creepers must be in the same boat at the same time.", tooltipimg: "Goal Tooltip Images/2creepers1boat.jpg", tags: [Action, Combat, Overworld]},
	{name: "Trade with a Villager", difficulty: -1, tags: [Village, Action, Overworld]},
	{name: "(2-3) Different Coloured Shields", difficulty: -1, tags: [Item, Colour, Overworld]},
	{name: "Dead Bush", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "(15-32) Grass", difficulty: -1, tooltiptext: "The tall stuff, NOT the block.", tooltipimg: "Goal Tooltip Images/TallGrass.jpg", tags: [Item, Overworld]},
	{name: "Cyan Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Magenta Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Red Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Orange Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Yellow Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Green Dye", difficulty: -1, reactant: ["UseFurnace"], infrequency: 10, tags: [Item, RareBiome, Overworld]},
	{name: "Pink Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Purple Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Lime Dye", difficulty: -1, infrequency: 10, tags: [Item, Overworld]},
	{name: "Never Sleep", difficulty: -1, catalyst: ["Sleep"], tags: [Never, Overworld]},
	{name: "Grow a Huge Mushroom", difficulty: -1, tags: [Action]},
	{name: "Water, Lava and Milk Bucket", difficulty: -1, antisynergy: ["BucketTypes", "WaterBucket", "LavaBucket", "MilkBucket"], reactant: ["UseBuckets"], tags: [Item, Overworld]},
	{name: "(5-7) Different Flowers", difficulty: -1, antisynergy: ["Flowers"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(3-6) Colours of Concrete", difficulty: -1, antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(3-6) Colours of Glazed Terracotta", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["GlazedColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (3-6) colours of Beds next to each other", difficulty: -1, antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Finish where you spawned using a Compass", difficulty: -1, tooltiptext: "Be stood close enough to spin your compass within a couple blocks at the end of the game.", tooltipimg: "Goal Tooltip Images/Compass.jpg", tags: [Action, Overworld, Finish]},
	{name: "(32-64) Stone", difficulty: -1, tooltiptext: "NOT Cobblestone.", tooltipimg: "Goal Tooltip Images/Stone.jpg", antisynergy: ["Stone"], infrequency: 2, reactant: ["UseFurnace"], tags: [Item, Overworld]},
	{name: "Kill (4-8) passive mobs with only fire", difficulty: -1, tooltiptext: "Don't hurt the passive mob any other way, only with Fire.", reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Kill a Creeper with only fire", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Combat, Overworld]},
	{name: "(32-64) Iron Nuggets", difficulty: -1, tags: [Item]},
	{name: "(32-64) Gold Nuggets", difficulty: -1, tags: [Item]},
	{name: "(16-32) Rotten Flesh", difficulty: -1, antisynergy: ["RotFlesh"], infrequency: 2, tags: [Item]},
	{name: "(16-64) Redstone", difficulty: -1, antisynergy: ["Redstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Golden Carrot", difficulty: -1, tags: [Item]},
	{name: "Rotten Flesh, Spider Eye, Bone, Gunpowder and Ender Pearl", difficulty: -1, tags: [Item, Overworld]},
	{name: "(32-64) Feathers", difficulty: -1, antisynergy: ["Feathers"], infrequency: 2, tags: [Item]},
	{name: "(2-10) Lily Pads", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "(65-128) Sticks", difficulty: -1, antisynergy: ["Sticks"], infrequency: 2, tags: [Item]},
	{name: "Wear 4 different colour Leather Armour at the same time", difficulty: -1, reactant: ["WearArmour"], tags: [Item, Colour, Overworld]},
	{name: "(15-32) Seagrass", difficulty: -1, antisynergy: ["Seagrass"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(65-128) Oak Wood Planks", difficulty: -1, antisynergy: ["OakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Spruce Wood Planks", difficulty: -1, antisynergy: ["SprucePlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Birch Wood Planks", difficulty: -1, antisynergy: ["BirchPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Dark Oak Wood Planks", difficulty: -1, antisynergy: ["DarkOakPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(65-128) Acacia Wood Planks", difficulty: -1, antisynergy: ["AcaciaPlanks"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Oak Logs", difficulty: -1, antisynergy: ["OakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Spruce Logs", difficulty: -1, antisynergy: ["SpruceLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Birch Logs", difficulty: -1, antisynergy: ["BirchLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Dark Oak Logs", difficulty: -1, antisynergy: ["DarkOakLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Acacia Logs", difficulty: -1, antisynergy: ["AcaciaLogs"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Oak Wood", difficulty: -1, antisynergy: ["OakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Spruce Wood", difficulty: -1, antisynergy: ["SpruceWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Birch Wood", difficulty: -1, antisynergy: ["BirchWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Dark Oak Wood", difficulty: -1, antisynergy: ["DarkOakWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Acacia Wood", difficulty: -1, antisynergy: ["AcaciaWood"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Oak Wood", difficulty: -1, antisynergy: ["StrippedOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Spruce Wood", difficulty: -1, antisynergy: ["StrippedSpruceWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Birch Wood", difficulty: -1, antisynergy: ["StrippedBirchWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Dark Oak Wood", difficulty: -1, antisynergy: ["StrippedDarkOakWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(11-20) Stripped Acacia Wood", difficulty: -1, antisynergy: ["StrippedAcaciaWood"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Oak Logs", difficulty: -1, antisynergy: ["StrippedOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Spruce Logs", difficulty: -1, antisynergy: ["StrippedSpruceLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Birch Logs", difficulty: -1, antisynergy: ["StrippedBirchLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Dark Oak Logs", difficulty: -1, antisynergy: ["StrippedDarkOakLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "(16-32) Stripped Acacia Logs", difficulty: -1, antisynergy: ["StrippedAcaciaLog"], reactant: ["AxeUse"], infrequency: 25, tags: [Item, Overworld]},
	{name: "Tropical Fish", difficulty: -1, tags: [Item, Ocean, Overworld]},
	{name: "Pufferfish", difficulty: -1, tags: [Item, Ocean, Overworld]},
	{name: "(6-15) Raw Cod", difficulty: -1, antisynergy: ["RawCod"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(4-7) Raw Salmon", difficulty: -1, antisynergy: ["RawSalmon"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Never use a Boat", difficulty: -1, tags: [Never, Overworld]},
	{name: "Get a Fish into the Nether", difficulty: -1, reactant: ["Pacifist"], tags: [Nether, Action, Overworld]},
	{name: "(11-20) Dried Kelp Blocks", difficulty: -1, antisynergy: ["KelpBlocks"], tags: [Item, Ocean, Overworld]},
	{name: "Drown a Zombie", difficulty: -1, tags: [Action, Combat, Overworld]},
	{name: "(2-5) Gunpowder", difficulty: -1, antisynergy: ["Gunpowder"], infrequency: 2, tags: [Item]},
	{name: "(2-5) Spider Eyes", difficulty: -1, antisynergy: ["SpiderEye"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(4-5) Different Edible Items", difficulty: -1, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", antisynergy: ["EdibleItems"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Breed (2-4) sets of mobs", difficulty: -1, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, Stat]},
	{name: "Crouch a distance of (100-200) meters", difficulty: -1, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Never use Debug (F3)", difficulty: -1, tags: [Never]},
	{name: "Ring a Bell from 10 blocks away", difficulty: -1, tags: [Action, Village, Overworld]},
	{name: "Repair an Item with a Grindstone", difficulty: -1, tags: [Action]},
	{name: "(2-6) Sweet Berries", difficulty: -1, tags: [Item, Overworld, RareBiome]},
	{name: "Banner Pattern", difficulty: -1, tooltiptext: "Any kind of Banner Pattern.", tags: [Item, Overworld]},
	{name: "Drink a Suspicious Stew", difficulty: -1, reactant: ["EatNonMeat"], tags: [Item, Overworld]},
	{name: "Give a Fox a Sword", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Honey Bottle", difficulty: -1, antisynergy: ["Honey"], infrequency: 2, tags: [Item, Overworld]},
	{name: "3 Honeycombs", difficulty: -1, antisynergy: ["Honeycomb"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(2-6) Basalt", difficulty: -1, tags: [Item, Nether]},
	{name: "(2-6) Blackstone", difficulty: -1, tags: [Item, Nether]},
	{name: "Fill all 4 slots of a Soul Campfire with Porkchops", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Nether, Combat]},
	{name: "Soul Lantern", difficulty: -1, tags: [Item, Nether]},
	{name: "Open a Door with a Target Block from 10 blocks away", difficulty: -1, tooltiptext: "YOU have to be 10 blocks away, not the Target Block from the Door.", tooltipimg: "Goal Tooltip Images/TargetAndDoor.jpg",  tags: [Action, Overworld]},
	{name: "Carrot on a Stick", difficulty: -1, tags: [Item]},
	{name: "Barter with a Piglin", difficulty: -1, tags: [Action, Nether]},
	{name: "Become Nauseous", difficulty: -1, reactant: ["EatMeat"], tags: [Item, Ocean, Overworld]},
	{name: "Enchanted item", difficulty: -1, tags: [Item]},
	{name: "Remove an Enchantment with a Grindstone", difficulty: -1, tags: [Action]},
	{name: "Never use a Sword", difficulty: -1, catalyst: ["SwordUse"], tooltiptext: "Never use a Sword for Combat or Block Breaking. Holding or crafting is fine.", tooltipimg: "Goal Tooltip Images/NoSword.jpg", tags: [Never]},
	{name: "Carnivore", difficulty: -1, tooltiptext: "Only eat meat.", tooltipimg: "Goal Tooltip Images/NoBread.jpg", antisynergy: ["Food"], tags: [Never, Action], catalyst: ["EatNonMeat"]},
	{name: "Clean a Pattern off a Banner", difficulty: -1, tags: [Action, Overworld]},
	{name: "(5-7) Different Gold Items", difficulty: -1, antisynergy: ["GoldItems"], tooltiptext: "Any item with 'Gold' in its name (yes, even Ingots and Ores).", tags: [Item]},
	{name: "(33-64) Sand", difficulty: -1, antisynergy: ["Sand"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(11-32) Sandstone", difficulty: -1, antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(11-32) Cut Sandstone", difficulty: -1, antisynergy: ["Sandstone"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(6-15) Paper", difficulty: -1, antisynergy: ["Paper"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(3-6) Coal Blocks", difficulty: -1, reactant: ["NeverCoal"], tags: [Item]},
	{name: "(2-5) Apples", difficulty: -1, antisynergy: ["Apples"], tags: [Item, Overworld]},
	{name: "Tame a Horse", difficulty: -1, tags: [Action, Overworld]},
	{name: "Hatch a Chicken from an Egg", difficulty: -1, tags: [Action, Overworld]},
	{name: "Empty a Cauldron without Buckets or Bottles", difficulty: -1, tooltiptext: "You can fill the Cauldron with Water however you want, just don't use Buckets or Bottles to empty it.", tags: [Action, Overworld]},
	{name: "Sleep in a Villager's bed", difficulty: -1, reactant: ["Sleep"], tags: [Action, Village, Overworld]},
	{name: "Set fire to a Villager's House", difficulty: -1, tags: [Action, Village, Overworld]},
	{name: "Emerald", difficulty: -1, tags: [Item, Overworld]},

	// Medium (2)
	{name: "(6-7) Different Edible Items", difficulty: -1, tooltiptext: "Raw and Cooked variants count as one (e.g. Raw Beef and Steak).", tooltipimg: "Goal Tooltip Images/RawAndCooked.jpg", antisynergy: ["EdibleItems"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Beetroot Soup", difficulty: -1, tags: [Item, Overworld]},
	{name: "Place a Cactus in a Flower Pot", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "Detonate a TNT-Minecart", difficulty: -1, tags: [Action, Overworld]},
	{name: "(10-30) Magma Blocks", difficulty: -1, tags: [Item]},
	{name: "Damaged Anvil", difficulty: -1, tags: [Item]},
	{name: "(16-64) Melon Slices", difficulty: -1, tags: [Item, Overworld]},
	{name: "Never wear any Armour", difficulty: -1, catalyst: ["WearArmour"], antisynergy: ["NeverWearArmour"], tags: [Never]},
	{name: "Get a Skeleton's Bow", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "Kill Skeletons until you get the rare Bow drop from one.", tags: [Item, Combat]},
	{name: "Diamond Block", difficulty: -1, antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "(2-3) Lapis Lazuli Blocks", difficulty: -1, tags: [Item, Overworld]},
	{name: "(3-5) Different Saplings", difficulty: -1, tooltiptext: "Crimson and Warped Fungi don't count!", tags: [Item, Overworld]},
	{name: "Tame a Wolf", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "6 Fire Charges", difficulty: -1, tags: [Item, Nether, Combat]},
	{name: "(2-3) Magma Cream", difficulty: -1, tags: [Item, Nether, Combat]},
	{name: "Create an Iron Golem", difficulty: -1, tags: [Action, Overworld]},
	{name: "Eye of Ender", difficulty: -1, reactant: ["Pacifist"], antisynergy: ["EyeOfEnder"], tags: [Item, Nether, Combat]},
	{name: "Rabbit Stew", difficulty: -1, tags: [Item, Overworld]},
	{name: "Potion of Fire Resistance", difficulty: -1, infrequency: 12, tags: [Item, Nether]}, // no Pacifist reactant and no Combat tag (Blaze Powder), no Overworld tag (Water Bottles), because can be bartered
	{name: "Potion of Healing", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Poison", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Harming", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Regeneration", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Slowness", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Strength", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Swiftness", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Weakness", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
	{name: "Potion of Leaping", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, RareBiome, Overworld, Combat]},
	{name: "Potion of Slow Falling", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Combat, Overworld]},
	{name: "Potion of the Turtle Master", difficulty: -1, infrequency: 12, reactant: ["Pacifist"], tags: [Item, Nether, Ocean, Overworld, Combat]},
	{name: "Finish by jumping from top to bottom of the world", difficulty: -1, tooltiptext: "Dig a hole to Bedrock, build to Y=256 (height limit), then jump from top to bottom at the end of the Bingo.", tooltipimg: "Goal Tooltip Images/FinishTopToBottom.jpg", tags: [Action, Build, Overworld, Finish]},
	{name: "Vegetarian", difficulty: -1, tooltiptext: "Never eat meat, including fish.", tooltipimg: "Goal Tooltip Images/NoFish.jpg", antisynergy: ["Food"], tags: [Never, Action], catalyst: ["EatMeat"]},
	{name: "Kill yourself with your own arrow", difficulty: -1, reactant: ["Pacifist"], tags: [Action]},
	{name: "Get a '... whilst trying to escape ...' Death message", difficulty: -1, tooltiptext: "Example: 'PLAYER' drowned whilst trying to escape a Skeleton.", tags: [Action]},
	{name: "Finish on top of the world", difficulty: -1, tooltiptext: "Build up to Y=256 (height limit) and stand on the top at the end of the Bingo.", tooltipimg: "Goal Tooltip Images/FinishTop.jpg", tags: [Action, Build, Finish]},
	{name: "Kill a hostile mob with Gravel", difficulty: -1, reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat]},
	{name: "Kill a hostile mob with Sand", difficulty: -1, reactant: ["Pacifist"], antisynergy: ["KillFallingBlock"], infrequency: 2, tags: [Action, Combat, Overworld]},
	{name: "Put a Carpet on a Llama", difficulty: -1, tags: [RareBiome, Action, Overworld]},
	{name: "Activate a (4-6)x(4-6) Nether Portal (not counting corners)", difficulty: -1, tooltiptext: "Width/height of the Obsidian frame, disregarding corners (or in other words, width/height of the—once activated—purple portal area).", tooltipimg: "Goal Tooltip Images/Portal.jpg", tags: [Action, Build, Nether]},
	{name: "(3-10) Obsidian", difficulty: -1, tags: [Item]},
	{name: "(5-7) Iron Blocks", difficulty: -1, antisynergy: ["IronBlocks"], infrequency: 2, tags: [Item]},
	{name: "(2-4) Gold Blocks", difficulty: -1, antisynergy: ["GoldBlocks"], infrequency: 2, tags: [Item]},
	{name: "Daylight Detector", difficulty: -1, tags: [Item, Overworld, Nether]},
	{name: "Enchanted Golden Sword", difficulty: -1, tags: [Item]},
	{name: "(8-11) Colours of Wool", difficulty: -1, antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(8-11) Colours of Terracotta", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(7-10) Colours of Glazed Terracotta", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["GlazedColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(7-10) Colours of Concrete", difficulty: -1, antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (7-10) colours of Beds next to each other", difficulty: -1, antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Power a Redstone Lamp", difficulty: -1, tags: [Action, Overworld]},
	{name: "(8-10) Different Flowers", difficulty: -1, antisynergy: ["Flowers"], infrequency: 2, tags: [Item, Overworld]},
	{name: "Put a Zombified Piglin in Water", difficulty: -1, tags: [Action, Nether, Overworld]},
	{name: "Place an Iron, Gold and Diamond block on top of each other", difficulty: -1, tags: [Build]},
	{name: "Kill a hostile mob with an Anvil", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Level (16-26)", difficulty: -1, antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "(2-3) Different Seeds", difficulty: -1, tooltiptext: "Any item with \"Seeds\" in the name.", tags: [Item, Overworld]},
	{name: "Wear 4 Different Armour types at the same time", difficulty: -1,  tooltiptext: "Example: GOLD shoes, LEATHER Trousers, IRON Chestplate and DIAMOND Helmet.", tooltipimg: "Goal Tooltip Images/4Armour.jpg", reactant: ["WearArmour"], tags: [Action]},
	{name: "Fill a Hopper with 320 items", difficulty: -1, tags: [Action, Item]},
	{name: "(16-32) Red Nether Brick Blocks", difficulty: -1, reactant: ["UseFurnace"], tags: [Item, Nether]},
	{name: "(16-32) Spectral Arrows", difficulty: -1, tags: [Item, Nether]},
	{name: "(33-64) Rotten Flesh", difficulty: -1, antisynergy: ["RotFlesh"], infrequency: 2, tags: [Item]},
	{name: "(16-32) Ink Sacs", difficulty: -1, antisynergy: ["InkSacs"], infrequency: 2, tags: [Item, Overworld]},
	{name: "(5-9) Slimeballs", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "Use a Lead on a Rabbit", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "Firework Star", difficulty: -1, tags: [Item, Overworld]},
	{name: "Hang a mob with a Lead", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "Suspend a mob in mid air using Fences and a Lead.", tooltipimg: "Goal Tooltip Images/HangingLead.jpg", tags: [Action, RareBiome, Overworld]},
	{name: "Blaze Rod", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Ghast Tear", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Never use Coal", difficulty: -1, tooltiptext: "Never use Coal for any crafting recipes or fuel in a Furnace, CAN use Charcoal.", catalyst: ["NeverCoal"], tooltipimg: "Goal Tooltip Images/NoCoal.jpg", tags: [Never]},
	{name: "(32-64) Glowstone Dust", difficulty: -1, tags: [Item, Nether]},
	{name: "(10-32) Item Frames", difficulty: -1, tags: [Item]},
	{name: "(3-4) Different Diamond Items", difficulty: -1, antisynergy: ["DiamondItems"], tooltiptext: "Any item with 'Diamond' in its name (yes, even itself).", tags: [Item]},
	{name: "(2-4) Prismarine Crystals", difficulty: -1, infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Dig straight down to Bedrock from Sea level (1x1 hole)", difficulty: -1, tooltiptext: "Sea Level is Y=63, but starting from higher is fine.", tags: [Action, Overworld]},
	{name: "Deplete an Iron Sword", difficulty: -1, reactant: ["SwordUse"], tooltiptext: "Use an Iron Sword until it breaks, check the 'Items' statistics screen!", tooltipimg: "Goal Tooltip Images/SwordDepelete.jpg", tags: [Action, Stat]},
	{name: "Saddle", difficulty: -1, tags: [Item]},
	{name: "Give a mob a Hat", difficulty: -1, tags: [Action, Combat]},
	{name: "Heart of the Sea", difficulty: -1, tags: [Item, Ocean, Overworld]},
	{name: "Phantom Membrane", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Combat, Overworld]},
	{name: "Add a Marker to a Map", difficulty: -1, tags: [Action, Overworld]},
	{name: "Water, Lava, Milk and Fish Bucket", difficulty: -1, antisynergy: ["BucketTypes", "WaterBucket", "LavaBucket", "MilkBucket", "FishBucket"], reactant: ["UseBuckets"], tooltiptext: "Can be any of the types of Fish.", tooltipimg: "Goal Tooltip Images/FishBucket.jpg", tags: [Item, Overworld]},
	{name: "Leash a Dolphin to a Fence", difficulty: -1, tags: [Action, Ocean, RareBiome, Overworld]},
	{name: "(21-32) Dried Kelp Blocks", difficulty: -1, antisynergy: ["KelpBlocks"], tags: [Item, Ocean, Overworld]},
	{name: "(6-15) Gunpowder", difficulty: -1, antisynergy: ["Gunpowder"], infrequency: 2, tags: [Item, Combat]},
	{name: "(6-15) Spider Eyes", difficulty: -1, antisynergy: ["SpiderEye"], infrequency: 2, tags: [Item, Combat, Overworld]},
	{name: "(4-6) Ender Pearls", difficulty: -1, antisynergy: ["EnderPearl"], infrequency: 2, tags: [Item, Combat]},
	{name: "Never use an Axe", difficulty: -1, catalyst: ["AxeUse"], tags: [Never]},
	{name: "Enchant an item", difficulty: -1, antisynergy: ["Enchant"], tags: [Action, Overworld]},
	{name: "Blue Shield with White Flower Charge Pattern", difficulty: -1, tags: [Item, Overworld]},
	{name: "Tame a Cat", difficulty: -1, tags: [Action, Village, Overworld]},
	{name: "Breed (5-7) sets of mobs", difficulty: -1, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["BreedAnimals"], infrequency: 2, tags: [Action, Stat]},
	{name: "Crouch a distance of (200-400) meters", difficulty: -1, tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["CrouchDistance"], infrequency: 2, tags: [Action, Stat]},
	{name: "Kill (75-100) mobs", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "Check the 'General' statistics screen!", antisynergy: ["MobKills"], tags: [Action, Combat, Stat]},
	{name: "(33-64) Seagrass", difficulty: -1, antisynergy: ["Seagrass"], infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "Kill an Iron Golem", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld]},
	{name: "Kill a mob with an End Crystal", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld, Nether, Combat]},
	{name: "Never Craft Sticks", difficulty: -1, tags: [Never, Overworld]}, // Overworld because can't get sticks in the Nether without crafting them
	{name: "Light a Campfire from 10 blocks away", difficulty: -1, tags: [Action]},
	{name: "Max Scale Map", difficulty: -1, tooltiptext: "You don't need to complete it, just zoom it out with a Cartography Table.", tags: [Item, Overworld]},
	{name: "Ignite a TNT with a Lectern", difficulty: -1, tags: [Action, Overworld]},
	{name: "Kill a hostile mob with a Sweet Berry Bush", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld, Combat, RareBiome]},
	{name: "Get a Pillager's Crossbow", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "Kill Pillagers until you get a rare Crossbow drop from one.", tags: [Item, Combat, Overworld, RareBiome]},
	{name: "Ominous Banner", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Combat, Overworld]},
	{name: "Gain a Fox's Trust", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Honey Block", difficulty: -1, antisynergy: ["Honey"], infrequency: 2, tags: [Action, Overworld]},
	{name: "3 Honeycomb Blocks", difficulty: -1, antisynergy: ["Honeycomb"], infrequency: 2, tags: [Action, Overworld]},
	{name: "Repair an Iron Golem", difficulty: -1, tags: [Action, Overworld, Village]},
	{name: "Grow a Tree with a Bee Nest attached", difficulty: -1, tags: [Action, Overworld]},
	{name: "(16-32) Warped Stem", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Warped Stem", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Warped Hyphae", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Warped Hyphae", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Warped Planks", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Crimsom Stem", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Crimsom Stem", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Crimsom Hyphae", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Stripped Crimsom Hyphae", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "(16-32) Crimsom Planks", difficulty: -1, infrequency: 25, tags: [Item, Nether]},
	{name: "Block of Quartz", difficulty: -1, tags: [Item, Nether]},
	{name: "(Try to) use a Respawn Anchor in the Overworld", difficulty: -1, tags: [Action, Nether]},
	{name: "Warped Fungus on a Stick", difficulty: -1, tags: [Item, Nether]},
	{name: "Convert a Hoglin into a Zoglin", difficulty: -1, tags: [Action, Nether, Combat]},
	{name: "Ride a Strider", difficulty: -1, tags: [Action, Nether]},
	{name: "Damage a Strider with Water", difficulty: -1, tags: [Action, Nether]},
	{name: "(6-15) Bamboo", difficulty: -1, tags: [Item, Overworld, RareBiome]},
	{name: "Crying Obsidian", difficulty: -1, tags: [Item]},
	{name: "Kill yourself with an Ender Pearl", difficulty: -1, tooltiptext: "Need to die to the small fall damage taken from using a Pearl.", tooltipimg: "Goal Tooltip Images/EnderPearl.jpg", reactant: ["Pacifist"], tags: [Action]},
	{name: "Grass Block", difficulty: -1, tooltiptext: "If you don't have Silk Touch, I know a guy who might pick one up for you...", tooltipimg: "Goal Tooltip Images/GrassBlock.jpg", tags: [Item, Overworld]},
	{name: "Bounce on a Slime Block", difficulty: -1, tooltiptext: "Get a Slime Block, place it on the ground and give it a good old bouncin' on.", tooltipimg: "Goal Tooltip Images/SlimeBlock.jpg", tags: [Action, Overworld]},
	{name: "Full Gold Armour", difficulty: -1, tags: [Item]},
	{name: "Brown Wool", difficulty: -1, tags: [Item, Overworld]},
	{name: "Grow a Huge Nether Fungus", difficulty: -1, antisynergy: ["GrowFungus"], tags: [Action, Nether]},
	{name: "Put a Chest on a Donkey", difficulty: -1, tags: [Action, Overworld]},
	{name: "Never place Torches", difficulty: -1, tooltiptext: "Never place normal Torches, you CAN craft with them. Other types of Torches are allowed.", tags: [Never]},
	{name: "Scute", difficulty: -1, antisynergy: ["TurtleShell"], tags: [Item, Ocean, Overworld]},

	// Hard (3)
	{name: "Create an Enchantment requiring level 10+", difficulty: -1, tags: [Action, Overworld]},
	{name: "Milk a Mooshroom", difficulty: -1, infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Shear a Mooshroom", difficulty: -1, infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "(2-5) Sea Lanterns", difficulty: -1, tags: [Item, Ocean, Overworld]},
	{name: "Sponge", difficulty: -1, tooltiptext: "DRY Sponge, not a Wet one", tooltipimg: "Goal Tooltip Images/Sponge.jpg", tags: [Item, Ocean, Overworld]},
	{name: "Listen to a Music Disc", difficulty: -1, tags: [Item]},
	{name: "(11-14) Different Flowers", difficulty: -1, antisynergy: ["Flowers"], infrequency: 3, tags: [Item, RareBiome, Overworld]},
	{name: "(2-4) Diamond Blocks", difficulty: -1, antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "Get a Zombified Piglin's Sword", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "Kill Zombified Piglins until you get a rare drop from one, it being their Golden Sword.", tooltipimg: "Goal Tooltip Images/GoldenSword.jpg", tags: [Action, Combat, Nether]},
	{name: "Finish by launching Fireworks of (5-10) Different Colours", difficulty: -1, tags: [Action, Item, Colour, Overworld, Finish]},
	{name: "Nametag an Enderman", difficulty: -1, tags: [Action, Combat, Overworld]},
	{name: "Finish on top of a Blaze Spawner", difficulty: -1, tooltiptext: "Be stood on top of a Blaze Spawner at the end of the game.", tags: [Action, Nether, Combat, Finish]},
	{name: "(12-14) Colours of Wool", difficulty: -1, antisynergy: ["WoolColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(12-14) Colours of Terracotta", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["TerracottaColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(11-14) Colours of Glazed Terracotta", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["GlazedColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "(11-14) Colours of Concrete", difficulty: -1, antisynergy: ["ConcreteColour"], infrequency: 4, tags: [Item, Colour, Overworld]},
	{name: "Place (11-14) colours of Beds next to each other", difficulty: -1, antisynergy: ["BedColour"], infrequency: 4, tags: [Build, Colour, Overworld]},
	{name: "Poison a Parrot", difficulty: -1, reactant: ["Pacifist"], infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Tame a Parrot", difficulty: -1, infrequency: 2, tags: [Action, RareBiome, Overworld]},
	{name: "Ice Block on top of a Magma Block", difficulty: -1, tags: [Item, Build, Overworld]},
	{name: "Level (27-37)", difficulty: -1, antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	{name: "Build a (2-4)x(2-4)x(2-4) Ice cube", difficulty: -1, tooltiptext: "You can choose what shall be the width/length/height.", tooltipimg: "Goal Tooltip Images/IceCube.jpg", tags: [Build, Overworld]},
	{name: "Finish on top of a stairway to Heaven", difficulty: -1, tooltiptext: "Using Stairs, build up to Y=256 (height limit) and stand on top at the end of the Bingo. (If you need to jump over a block, it's not a finished stairway.)", tooltipimg: "Goal Tooltip Images/FinishStairs.jpg", tags: [Build, Overworld, Finish]},
	{name: "Get a Ghast into the Overworld", difficulty: -1, tags: [Action, Nether, Overworld]},
	{name: "Enchanted Golden Apple", difficulty: -1, tags: [Item]},
	{name: "Never wear Armour or use Shields", difficulty: -1, tooltiptext: "You can use Armour/Shields in crafting, but cannot wear the Armour or block with Shields", catalyst: ["WearArmour"], antisynergy: ["NeverWearArmour"], tags: [Never]},
	{name: "Kill a mob that is wearing Full Iron Armour", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Combat]},
	{name: "Enchant 5 different items", difficulty: -1, antisynergy: ["Enchant"], tags: [Action, Overworld]},
	{name: "Never use Buckets", difficulty: -1, catalyst: ["UseBuckets"], tags: [Never]},
	{name: "Conduit", difficulty: -1, tags: [Item, Ocean, Overworld]},
	{name: "(2-5) types of Dead Coral Blocks", difficulty: -1, tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "(16-32) Sea Pickles", difficulty: -1, tags: [Item, Ocean, RareBiome, Overworld]},
	{name: "Get a '... didn't want to live in the same world as ...' Death message", difficulty: -1, tags: [Action]},
	{name: "Cookie", difficulty: -1, tags: [Item, Overworld]},
	{name: "Grow a Full Jungle Tree", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "(2-10) Prismarine Shards", difficulty: -1, infrequency: 2, tags: [Item, Ocean, Overworld]},
	{name: "(16-32) Jungle Logs", difficulty: -1, infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(11-20) Jungle Wood", difficulty: -1, infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(11-20) Stripped Jungle Wood", difficulty: -1, reactant: ["AxeUse"], infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(11-20) Stripped Jungle Logs", difficulty: -1, reactant: ["AxeUse"], infrequency: 4, tags: [Item, RareBiome, Overworld]},
	{name: "(5-7) Different Diamond Items", difficulty: -1, antisynergy: ["DiamondItems"], tooltiptext: "Any item with 'Diamond' in its name (yes, even itself).", tags: [Item]},
	{name: "Destroy a Monster Spawner", difficulty: -1, tags: [Action, Combat]},
	{name: "(32-64) Popped Chorus Fruit", difficulty: -1, tags: [Item, End]},
	{name: "Get a Villager into The End", difficulty: -1, tags: [Action, End, Village]},
	{name: "(5-16) Dragon's Breath", difficulty: -1, tags: [Item, Combat, End]},
	{name: "Dragon Egg", difficulty: -1, tags: [Item, Combat, End]},
	{name: "Complete a full size Map", difficulty: -1, antisynergy: ["CompleteMap"], tags: [Action, Overworld]},
	{name: "Be killed by a Villager", difficulty: -1, tooltiptext: "Sometimes you need to DISPENSE some DEFENCE.", tags: [Village, Overworld, Stat, Combat]},
	{name: "Save yourself with a Totem of Undying", difficulty: -1, tags: [Item, Overworld]},
	{name: "Every type of Sword", difficulty: -1, infrequency: 2, antisynergy: ["EverySword"], tooltiptext: "Wooden, Gold, Iron, Diamond and yes, even Netherite.", tags: [Item, Nether, Netherite]},
	{name: "Every type of Pickaxe", difficulty: -1, infrequency: 2, antisynergy: ["EveryPickaxe"], tooltiptext: "Wooden, Gold, Iron, Diamond and yes, even Netherite.", tags: [Item, Nether, Netherite]},
	{name: "Pacifist", difficulty: -1, tooltiptext: "Never kill any creature, as per the statistics screen", catalyst: ["Pacifist"], tags: [Never, Stat]},
	{name: "Finish by building a Scaffolding tower, then removing it", difficulty: -1, tooltiptext: "Build a 1x1 Scaffolding Tower from Bedrock to Y=256 (height limit) and then knock it all down as the final goal.", tags: [Build, Overworld, Finish]},
	{name: "Feed a Panda a Cake", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Make two Pandas breed", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Disarm a Pillager", difficulty: -1, tooltiptext: "Get a Pillager to not be holding any Weapons", tags: [Action, Overworld, Combat, RareBiome]},
	{name: "Stun a Ravager", difficulty: -1, tags: [Action, Overworld, Combat, Village]},
	{name: "Become Hero of the Village", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld, Combat, Village]},
	{name: "Gain an Ocelot's Trust", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "12 Eyes of Ender", difficulty: -1, reactant: ["Pacifist"], tooltiptext: "How good is your luck?", tags: [Item, Nether, Combat]},
	{name: "Netherite Ingot", difficulty: -1, tags: [Item, Nether, Netherite]},
	{name: "Wither Skull", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Combat, RareBiome]},
	{name: "Gilded Blackstone", difficulty: -1, tags: [Item, Nether, RareBiome]},
	{name: "Make a Compass point to a Lodestone", difficulty: -1, tags: [Action, Nether, Netherite]},
	{name: "Give a Piglin Brute an Enchanted Axe", difficulty: -1, tags: [Action, Nether, Combat, RareBiome]},
	{name: "Build a 6x6 Scaffolding n Shape (not counting corners)", difficulty: -1, tooltiptext: "Width/height of the inside frame, disregarding corners.", tooltipimg: "Goal Tooltip Images/ScaffingN.jpg", tags: [Build, Overworld]},
	{name: "(2-5) Honey Blocks", difficulty: -1, antisynergy: ["Honey"], infrequency: 2, tags: [Action, Overworld]},
	{name: "(6-15) Honeycomb Blocks", difficulty: -1, antisynergy: ["Honeycomb"], infrequency: 2, tags: [Action, Overworld]},
	{name: "Kill a Wandering Trader", difficulty: -1, reactant: ["Pacifist"], tags: [Action, Overworld, Combat]},
	{name: "Cure a Zombie Villager", difficulty: -1, tags: [Action, Overworld]},
	{name: "Throw a Mending Book into Lava", difficulty: -1, tags: [Action]},
	{name: "Never smelt with Furnaces", difficulty: -1, tooltiptext: "You can use Furnaces in crafting, but cannot use them for cooking or smelting", catalyst: ["UseFurnace"], tags: [Never]},
	{name: "Grow a Huge Nether Fungus in the Overworld", difficulty: -1, antisynergy: ["GrowFungus"], tags: [Action, Overworld, Nether]},
	{name: "(32-64) Dirt, Netherrack and End Stone", difficulty: -1, tags: [Item, Overworld, Nether, End]},
	{name: "Tame a Mule", difficulty: -1, tags: [Action, Overworld]},
	{name: "Convert a Carrot on a Stick into a Fishing Rod", difficulty: -1, tags: [Action, Overworld]},
	{name: "Skull Charge Banner Pattern", difficulty: -1, tags: [Item, Nether, Combat, RareBiome, Overworld]},
	{name: "Turtle Shell", difficulty: -1, antisynergy: ["TurtleShell"], tags: [Item, Ocean, Overworld]},

	// Very Hard (4)
	{name: "(5-7) Different Ores", difficulty: -1, tooltiptext: "Coal, Diamond, Emerald, Gold, Iron, Lapis Lazuli, Nether Quartz, Nether Gold and Redstone Ores are your choices.", tooltipimg: "Goal Tooltip Images/Ores.jpg", tags: [Item, Overworld]},
	{name: "(12-15) Different Potions", difficulty: -1, tooltiptext: "Splash, Lingering, Enhanced and Extended variants DON'T count!", reactant: ["Pacifist"], tags: [Item, Nether, Combat, Overworld]},
	{name: "Every type of Chestplate", difficulty: -1, tooltiptext: "Leather, Gold, Chainmail, Iron, Diamond and yes, even Netherite.", tooltipimg: "Goal Tooltip Images/chainmail chest.jpg", tags: [Item, Combat, Netherite]},
	{name: "Any mob head OTHER than a Wither Skeleton's", difficulty: -1, tooltiptext: "Dragon, Skeleton, Zombie or a Creeper Head. Wither Skeleton skulls do NOT count.", tags: [Item, Combat, Overworld]},
	{name: "Every colour of Dye", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["EveryColour"], infrequency: 2, tooltiptext: "Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!", tooltipimg: "Goal Tooltip Images/EveryColourOfDye.png", tags: [Item, Colour, Overworld]},
	{name: "Level 50", difficulty: -1, antisynergy: ["Level"], infrequency: 2, tags: [Stat]},
	//{name: "Fill a Double Chest with 3456 items", reactant: ["UseChests"], tags: [Item, Action]}, BOOOORRRRRRRINNG AND TOO EASY
	{name: "(16-32) Tipped Arrows", difficulty: -1, tags: [Item, Nether, Overworld]},
	{name: "Place 1 of each Mineral block on top of each other", difficulty: -1, tooltiptext: "Coal, Iron, Gold, Diamond, Redstone, Lapis, Emerald, Quartz and Netherite blocks.", tooltipimg: "Goal Tooltip Images/MineralBlocks.jpg", tags: [Item, Build, Overworld, Nether, Netherite]},
	{name: "Sleep in a Woodland Mansion", difficulty: -1, tags: [Action, RareBiome, Overworld]},
	{name: "(10-32) Mycelium", difficulty: -1, tags: [Item, RareBiome, Overworld]},
	{name: "5 types of Coral Blocks", difficulty: -1, tooltiptext: "The alive stuff, not the Dead Coral Blocks.", tooltipimg: "Goal Tooltip Images/CoralBlocks.jpg", tags: [Item, RareBiome, Ocean, Overworld]},
	{name: "(32-64) Blue Ice", difficulty: -1, tags: [Item, Overworld]},
	{name: "Fully power a Conduit", difficulty: -1, tags: [Item, Ocean, Build, Overworld]},
	{name: "Every item Diamonds are used to Craft", difficulty: -1, antisynergy: ["DiamondItems"], tooltiptext: "Block, Axe, Boots, Chestplate, Helmet, Hoe, Leggings, Pickaxe, Shovel, Sword, Enchantment Table, Firework Star and Jukebox.", tags: [Item]},
	{name: "Get a Shulker into the Overworld", difficulty: -1, tags: [Action, Combat, End, Overworld]},
	{name: "(5-10) Diamond Blocks", difficulty: -1, antisynergy: ["DiamondBlock"], infrequency: 2, tags: [Item]},
	{name: "Complete a full size Map in the End", difficulty: -1, antisynergy: ["CompleteMap"], tags: [Action, Overworld, End]},
	{name: "(32-64) Wither Roses", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Combat]},
	{name: "Get a Slimeball from a Panda", difficulty: -1, tags: [Item, Overworld, RareBiome]},
	{name: "2 Blocks of Netherite", difficulty: -1, tags: [Item, Nether, Netherite]},
	{name: "Full Netherite Armour and Tools", difficulty: -1, tags: [Item, Nether, Netherite]},
	{name: "Convert a Pig into a Zombified Piglin", difficulty: -1, tags: [Action, Overworld]},
	{name: "Trident", difficulty: -1, tags: [Item, Ocean, Combat, Overworld]},
	{name: "Tame a Skeleton Horse", difficulty: -1, tags: [Action, Overworld]},
	{name: "Make every colour of Parrot dance at the same time", difficulty: -1, tags: [Action, Overworld, RareBiome]},
	{name: "Place every colour of Bed next to each other", difficulty: -1, reactant: ["UseFurnace"], antisynergy: ["EveryColour"], infrequency: 2, tooltiptext: "Black, Blue, Brown, Cyan, Grey, Green, Light Blue, Light Grey, Lime, Magenta, Orange, Pink, Purple, Red, White and Yellow!", tooltipimg: "Goal Tooltip Images/EveryBed.jpg", tags: [Action, Colour, Overworld]},
	{name: "Kill an Enderman with only Endermites", difficulty: -1, tooltiptext: "Don't hurt the Enderman any other way, only with Endermites.", tags: [Action, Combat, End]},
	{name: "Get Regeneration from a Beacon", difficulty: -1, reactant: ["Pacifist"], tags: [Item, Nether, Overworld, Combat]},
];
